#! /bin/ksh
#$Id: rrevlog,v 1.3 2007/04/06 02:07:12 gw8440 Exp $
## modify to access prod server alias racercs gw 03/28/07

 if [ $# = "0" ]
    then
      echo  Usage: rrevlog filename subsystem_name/component_name "\007" >&2
      echo " Example: rrevlog xfcz001.cbl ceg/src"
      exit -2
  fi

  rverify $1 $2                                    # verify argument-name strings
  if [ $? != 0 ]
    then
    exit -1
  fi

##export RCSDIR=race:/prod/race
export RCSDIR=racercs:/prod/race


echo ================== RCS log ===========================
rev_log.ksh  $1 $2
#echo ======================================================
