#! /bin/ksh
#$Id: runlock,v 1.4 2007/04/06 02:07:19 gw8440 Exp rj132422 $
## modify to access prod server alias racercs gw 03/28/07

##export RCSDIR=race:/prod/race
export RCSDIR=racercs:/prod/race


 if [ $# = "0" ]
    then
      echo  Usage: runlock filename subsystem_name/component_name "\007" >&2
      exit -2
  fi

echo ========================= summary =====================================
rel_lock.ksh  $1 $2

 if [ $? = 0 ]              # good return code from rel_lock
  then
    echo File is now unlocked.
  fi
echo =======================================================================
