#!/usr/local/bin/perl 
#
# by: Khider Allos 1/1999
############################################################################
# Program to open delimited file and create fixed length fields
# records.
# It requires two parameter 'delimeter char' and file name
# check usage below
#
# 12/02/2004 JLW Modified script to correct logic errors.
#                Changed $#ARGV for > 0 when setting defaults
#                Changed if statement from = to ==.
############################################################################
# prints usage message
#

 $nfnm=split(/\//,$0);
 @fnm=split(/\//,$0);
  if ($#ARGV < 0  )
   {
   print STDERR "\nFunction: $fnm[$#fnm] converts file with delimited fields to fixed length fields.\n\n";
   print STDERR "   Usage: $fnm[$#fnm]  'delimited file' ['delimeter char'] ['fixed field size']\n\n";
   print STDERR "   Parms: 'delimited file' required delimited file name. \n\n";
   print STDERR "          'delimeter char' optional default delimiter '\"'.\n";
   print STDERR "          Note: enclose delimeter in single quote i.e. '*'.\n\n";
   print STDERR "          'fixed field size' optional default 25 characters. \n\n";

   die   "$!\n";
   }


# open input file as the second argument, kill program if not found.

open(DIN, $ARGV[0]) || die "Couldn't open $ARGV[0] $!\n"; # Open file


# Set default delimiter character to special char
# Generated by pressing ctrl plus h keys '`'

  $delm='`';

# Set default validate file delimiter character to  '`'

  $tdelm='`';

# set delimeter to first character of delimeter argument, if delimeter
# argument is provided.

# set validate delimeter to the delimeter argument, if delimeter
# argument is provided.

  if ($#ARGV > 0  )
   {
     $pdelm=substr($ARGV[1],0,1);
     $tdelm=$ARGV[1];
   }
  else
   {
     $pdelm=',';
     $tdelm=$pdelm;
   }

# Define form variable to be used in pack function as 25 char ascii
# filled with space

 $fsize="25";

 if ($#ARGV == 2 )
   {
    if ( $ARGV[2] > 1  )
    {
    $fsize=$ARGV[2];
    }
   }

  $fform="A"."$fsize";


$rec=0;
# process delimeted file records
while (<DIN>)    # While there is input
{

# Abort program, if file 1st 5 records contain no delimeter characters.
 if ( $rec > 5 && $rec < 10  )
 {
 die "Error: Delimter '$tdelm' is not found in file\!\n" if ( ! /$tdelm/ );
 }

if ( $pdelm == "," )
{
#clean delimeters "chars" to one delimeter

    s/$pdelm$pdelm$pdelm$pdelm$pdelm/$pdelm" "$pdelm" "$pdelm" "$pdelm" "$pdelm/g;

    s/$pdelm$pdelm$pdelm$pdelm/$pdelm" "$pdelm" "$pdelm" "$pdelm/g;

    s/$pdelm$pdelm$pdelm/$pdelm" "$pdelm" "$pdelm/g;

    s/$pdelm$pdelm/$pdelm" "$pdelm/g;

    s/$pdelm"$pdelm/"$pdelm/g;

    s/"$pdelm"/$delm/g;

    s/" +$pdelm"/$delm/g;

    s/" +$pdelm$pdelm/$delm/g;

    s/$pdelm"/$delm/g;

    s/"$pdelm/$delm/g;

    s/(\.\d\d)$pdelm(\d)/$1$delm$2/g;
    s/(\.\d)$pdelm(\d)/$1$delm$2/g;

    s/$delm(\d)$pdelm(\d)/$delm$1$delm$2/g;
    s/$delm(\d\d)$pdelm(\d)/$delm$1$delm$2/g;
    s/$delm(\d\d\d)$pdelm(\d)/$delm$1$delm$2/g;
    s/$delm(\d\d\d\d)$pdelm(\d)/$delm$1$delm$2/g;
    s/$delm(\d\d\d\d\d)$pdelm(\d)/$delm$1$delm$2/g;


 # die $_;
}
else
{
#clean delimeters char,char to one char
    s/$pdelm$pdelm$pdelm$pdelm$pdelm/$delm $delm $delm $delm $delm/g;
    s/$pdelm$pdelm$pdelm$pdelm/$delm $delm $delm $delm/g;
    s/$pdelm$pdelm$pdelm/$delm $delm $delm/g;
    s/$pdelm$pdelm/$delm $delm/g;

    s/$pdelm,$pdelm/$delm/g;

    s/$pdelm,/$pdelm/g;

    s/,$pdelm/$delm/g;
}

#put a space char in null fields

#change delimeter 1st and last character of a record
#if it is a delimeter character to one default delimeter

    s/^"//;
    s/^,//;
    s/^$pdelm//;
    s/"$//;
    s/,$//;
    s/$pdelm$//;

#remove  delimeter character from record 1st byte if it is found

#remove the line feed from the current record
    chop;
#split delimited fields into an array @fld
    @fld=split(/$delm/,$_);
#get the number of fields from input record into $nfld
    $nfld=split(/$delm/,$_);

#combine array fields @fld into $line string using pack and the format $fform
# for the number of fields $nfld
    $line=pack($fform x $nfld,@fld);
# write out the fixed length record with field length as defined in $fform
    printf ("%-250s\n", $line);

$rec++;
}
