# Entering precomp.mk

# Entering /ade/b/1663622200/oracle/buildtools/mkfile/prefix.mk

# Entering /ade/b/1663622200/oracle/buildtools/mkfile/defs.mk

SHELL=/bin/sh

AS_EXT=s
CC_EXT=cpp
LIB_EXT=a
OBJ_EXT=o
PLB_EXT=plb
SO_EXT=so
LOCK_EXT=lk
SQL_EXT=sql
SYM_EXT=sym
JAVA_EXT=java
CLASS_EXT=class
JAR_EXT=jar
ZIP_EXT=zip
DEF_EXT=def
BITCODE_EXT=bc

LIB_PREFIX=lib
LDLIBFLAG=-l
LDPATHFLAG=-L
PATHSEP= :
DEPLIB_EXT=$(LIB_EXT)
DEPSO_EXT=$(SO_EXT)

AR=ar
AS=as
AWK=awk
CAT=cat
CC=cc
CCC=CC
CD=cd
CHMOD=chmod
CP=cp
CPP=cpp
CPP_WITH_COMMENTS=cpp -C -std=c9x
CODECOV_TOOL_CCB=stattool.STABLE
CODECOV_TOOL_HTML=stattool.STABLE --ed-commands
DATE=date
ECHO=echo
ECHON=echo -n
EXEC=exec
FIND=find
FOLLOW=-follow
NOLEAF=-noleaf
GREP=grep
KILL=kill
SLEEP=sleep
LD=ld
LMAKE=make
LN=ln
LNS=ln -s
MKDIR=mkdir
MKDIRP=mkdir -p
MV=mv
MVF=mv -f
NM=nm
PERL=perl
RM=rm
RMF=rm -f
CPF=cp -f
RMRF=rm -rf
SED=sed
SORT=sort
TOUCH=touch
TR=tr
XARGS=xargs
LS=ls
ED=ed - -s

PERL_EXEC=$(PERL_EXEC_5_6)

ANT=ant

NULL_DEVICE=/dev/null

BINDIR=bin
LIBDIR=lib
JSRCDIR=jsrc
JLIBDIR=jlib
BINHOME=$(ORACLE_HOME)/$(BINDIR)/
LIBHOME=$(ORACLE_HOME)/$(LIBDIR)/

PRODHOME=$(ORACLE_HOME)/$(PRODUCT)/
PRODJORACLE_HOME=$(PRODHOME)$(JSRCDIR)/
PRODLIBHOME=$(PRODHOME)$(LIBDIR)/
PRODSOHOME=$(PRODLIBHOME)
PRODADMIN=$(PRODHOME)admin/
PRODDEFHOME=$(PRODADMIN)

ECHODO=$(BINHOME)echodo
GENSYSLIB=$(BINHOME)gensyslib
GENCLNTSH=$(BINHOME)genclntsh
GENCLNTST=$(BINHOME)genclntst
GENOCCISH=$(BINHOME)genoccish
GENAGTSH=$(BINHOME)genagtsh
GENNAFLG=$(BINHOME)gennaflg
GENAUTAB=$(BINHOME)genautab
MKMANIFEST=$(ORACLE_HOME)/buildtools/bin/mkjmanifest
GENORASDKBASE=$(BINHOME)genorasdksh -base
GENORASDKSH=$(BINHOME)genorasdksh

ARCHIVE=$(ECHODO) $(ARCREATE) $(LIB) $?
ARCHIVE2=$(ECHODO) $(ARCREATE) $(LIB2) $?
ARCHIVE_PIC=$(ECHODO) $(ARCREATE) $(PIC_LIB) $?
ARCHIVE2_PIC=$(ECHODO) $(ARCREATE) $(PIC_LIB2) $?
ARCHIVE_NOPIC=$(ECHODO) $(ARCREATE) $(NOPIC_LIB) $?
ARCHIVE2_NOPIC=$(ECHODO) $(ARCREATE) $(NOPIC_LIB2) $?
ARCHIVE_OBJ=$(AR) r $@ $*.$(OBJ_EXT)
ARCREATE=$(AR) cr$(ARLOCAL)
ARDELETE=$(AR) d$(ARLOCAL)
AREXTRACT=$(AR) x 
ARPRINT=$(AR) t
ARREPLACE=$(AR) r 
DOAR=$(ARCREATE) $@ $? 

JARCHIVE_OBJ=$(JAR) cv0f $@ $(JPKG_FILES) $(EXTRA_CLASS_FILES)
JARCREATE=$(JAR) cv0f
JARDELETE=$(ECHO) "no such thing"
JAREXTRACT=$(JAR) xf
JARPRINT=$(JAR) tvf
JARREPLACE=$(JAR) uf

CCARCREATE=$(CCC) -xar -o 

MAKE=$(LMAKE)
QUIET=>/dev/null 2>&1
QUIETE=2>/dev/null
SILENT=@

CTSCLEAN=clean
CTSCOMPTYPE=comp_ar1 _UNLOCK='$$(_unlock)' _LOCK='$$(_lock)' _RM='$$(_rm)' 
CTSDEPLIST=DEPLIST=/dev/null
CTSMAKEFLAGS=$(SILENT:@=--no-print-directory -s) $(CTSCLEAN) $(CTSCOMPTYPE) $(CTSDEPLIST)

CFLAGS=$(GFLAG) $(OPTIMIZE) $(CDEBUG) $(CCFLAGS) $(PFLAGS)\
	$(SHARED_CFLAG) $(USRFLAGS)
CFLAGSCC=$(GFLAG) $(OPTIMIZE) $(CDEBUG) $(CCFLAGSCC) $(PFLAGS)\
	$(SHARED_CFLAG) $(USRFLAGS)
PFLAGS=$(INCLUDE) $(SPFLAGS) $(LPFLAGS) $(PLSQLNCGFLAGS)

LD_SHARED_FLAG=$(SHARED_CFLAG)

LDCCOM=$(ADE_DEL_FILE_CMD) $(PURECMDS) $(CC) $(GFLAG) $(CCFLAGS) $(EXOSFLAGS) $(LDFLAGS)
LDCCOMCC=$(ADE_DEL_FILE_CMD) $(PURECMDS) $(CCC) $(GFLAG) $(CCFLAGSCC) $(EXOSFLAGS) $(LDFLAGS)
PURECMDS=$(PURELINK) $(PURIFY) $(PURECOV) $(QUANTIFY)
LINK=$(LDCCOM)
LINKCC=$(LDCCOMCC)
LDFLAGS=-o $@ $(LDPATHFLAG)$(PRODLIBHOME) $(LDPATHFLAG)$(LIBHOME)
LDLIBS=$(EXPDLIBS) $(EXOSLIBS) $(SYSLIBS) $(EXSYSLIBS) $(MATHLIB) $(USRLIBS)
MATHLIB=-lm
LINKLDLIBS=$(LDLIBS)
COBLDLIBS=$(LDLIBS)

SYSLIBLIST=$(LIBHOME)sysliblist
SYSLIBS=`$(CAT) $(SYSLIBLIST)`

NAETTOBJS=$(NAUTAB) $(NAETAB) $(NAEDHS)
TTLIBD=$(NETLIBD) $(LIBRDBMS_CLT) $(LIBMM) $(CORELIBD) $(LIBEPC) $(LIBCLNTSH)
ORACLETTLIBS1=$(NTZEOBJ) $(NETLIBS) $(NZLIBS) $(LLIBZTKG) $(LLIBRDBMS_CLT) $(LLIBMM) $(CORELIBS)\
       $(NETLIBS) $(LLIBRDBMS_CLT) $(LIBPLS_CLT) $(LLIBEPC) $(CORELIBS) \
       $(LLIBRDBMS_CLT) $(CORELIBS)
ORACLETTLIBS=$(ORACLETTLIBS1)
STATICTTLIBS=$(ORACLETTLIBS) $(LDLIBS)
TTLIBS=$(LLIBCLNTSH) $(STATICTTLIBS)
DEVTTLIBS=$(TTLIBS)
LINKTTLIBS=$(LLIBCLNTSH) $(ORACLETTLIBS) $(LINKLDLIBS)
COBTTLIBS=$(ORACLETTLIBS) $(COBLDLIBS)
SUIDLINKTTLIBS=$(LLIBCLNTSH) $(ORACLETTLIBS) $(SUIDLINKLDLIBS)

STATIC_ORACLETTLIBS=$(NTZEOBJ) $(NETLIBS) $(NZLIBS) $(LIBRDBMS_CLT) \
    $(LIBMM) $(CORELIBS) $(NETLIBS) $(LIBRDBMS_CLT) $(LIBPLS_CLT) \
    $(LIBEPC) $(CORELIBS) $(LIBRDBMS_CLT) $(CORELIBS)

SHARED_CLIENTLIBS=$(LLIBCLNTSH) $(LDFLAGSLIST)
STATIC_CLIENTLIBS=$(LLIBCLNTST) $(LDFLAGSLIST)
SHARED_LDCLIENTLIBS=$(SHARED_CLIENTLIBS) $(LDLIBS)
STATIC_LDCLIENTLIBS=$(STATIC_CLIENTLIBS) $(LDLIBS)

I_SYM=-I

LD_SHLIBS=$(SHLIBS)
DLOPENLIB_COMMAND=$(LD_SHLIB_COMMAND)
DLOPEN_SYM_COMMAND=$(SYM_COMMAND)
LD_SHLIB_COMMAND=$(SO_COMMAND)

MAJORVSN=11
MINORVSN=2
MIDTIERVSN=0
PATCHMAJORVSN=3
PATCHMINORVSN=0
BANNERVERSION=$(MAJORVSN).$(MINORVSN).$(MIDTIERVSN).$(PATCHMAJORVSN).$(PATCHMINORVSN)

# Exiting /ade/b/1663622200/oracle/buildtools/mkfile/defs.mk
# Entering /ade/b/1663622200/oracle/buildtools/mkfile/platform.mk

FAMILY=unix
PLATFORM=aix
PLATFORM64=aix64

STATIC_ORACLETTLIBS=$(LLIBCLNTST) $(LDFLAGSLIST)

LD_PT_OPTION=0x100000000
LD_PD_OPTION=0x110000000

MOTIFHOME=/usr/lpp/X11/

DIRSEP=/
PSEP=:

GMAKE=/usr/local/bin/gmake
LMAKE=/bin/make
MAKE=/bin/make
FIND=/bin/find
PS=ps -fe


JARCHIVE=@if echo ${JLIB} | egrep '\.jar' > /dev/null 2>&1;then $(ECHODO) $(JARCREATE) $(JLIB) $? ; else echo "warning: Bad JLIB: .$(JLIB)."; fi

GROUP=/etc/group

COMPOBJS=-b64
LINK=ld $(COMPOBJS) $(LDFLAGS)

LLIBTHREAD=-lpthreads

MOTIFLIBS=-L$(MOTIFHOME)lib -lXm -lXt -lX11 -lm
XLIBS=

EXOSFLAGS=
EXOSLIBS=-lld -lm

LIBPLS_CLT=$(LLIBPLS)

DEVTTLIBS=$(NETLIBS) $(LLIBRDBMS_CLT) $(NETLIBS) $(LLIBRDBMS_CLT)\
	$(LIBPLS_CLT) $(LLIBEPC) $(CORELIBS) $(EXPDLIBS) $(EXOSLIBS)\
	$(SYSLIBS) $(MATHLIB)

OPTIMIZE2=-O2
OPTIMIZE4=-O4
OPTIMIZE=-O3

AR=/bin/ar -X64
AR32=/bin/ar -X32
AS=/bin/as -a64
AS32=/bin/as -a32
LD=/bin/ld -b64
NM=/usr/ccs/bin/nm -X64
TR=/usr/bin/tr
CPP=/usr/local/bin/xlc -E -q64 $(CCFLAGS)
TOUCH=/bin/touch
KSMSIMP=$(ORACLE_HOME)/$(LIBDIR)/ksms.imp
CC=$(ORACLE_HOME)/bin/oraxlc $(ORAXLCFLAGS)
CCC=$(ORACLE_HOME)/bin/oraxlc -cpp $(ORAXLCFLAGS)

UNAMEV=/usr/bin/uname -v
AIXIMP=

CHMOD=/bin/chmod
CHGRP=/bin/chgrp
CHOWN=/bin/chown
ZIP=/usr/local/bin/zip
UNZIP_DIR_FLAG=-d


ASFLAGS=
ASPFLAGS=$(PFLAGS)


CCFLAGS_FOR_LOGGING=-qflag=s:s
NOKPIC_CCFLAGS=-q64 -DSS_64BIT_SERVER -qwarn64 -qinfo=uni -DAIXRIOS $(CCFLAGS_FOR_LOGGING) 
CCFLAGSCC=-q64 $(CCFLAGS_FOR_LOGGING) 

KPIC_OPTION=

SHARED_LDFLAG=
SHARED_CFLAG=
CCFLAGS=$(NOKPIC_CCFLAGS) $(KPIC_OPTION)



IMP_EXT=imp

DEF_EXT=exp

NMFLAGS=-B -h -g

DEF_COMMAND=$(GREP) -v ' U '  $(PRODLIBHOME)$(LIB_PREFIX)$*.$(NM_EXT) | $(GREP) -v "::" | $(GREP) -v "(" |$(GREP) -v "\.cc" | $(AWK) '{print $$3}' | $(SED) -e "s/\.//g" | $(GREP) -v "^_"| $(SORT) | $(UNIQ) > $@ ;

GEN_IMP=$(ORACLE_HOME)/buildtools/bin/gen_imp.sh
IMP_COMMAND=$(GEN_IMP) $(PRODLIBHOME)$(LIB_PREFIX)$*.$(LIB_EXT) $@

LD_PD_OPTION=0x110000000
LD_PT_OPTION=0x100000000 

LD_SHLIB_DEP= $(PRODDEFHOME)%.$(DEF_EXT) $(PRODLIBHOME)%.$(LIB_EXT) $(PRODDEFHOME)%.$(IMP_EXT)
DLOPENLIB_DEP=$(LD_SHLIB_DEP)

SHLIB_LD=$(LD) -o $(_FULL_LIBNAME) -G -bnoentry -L$(BOOTSTRAPLIB) -L$(LIBHOME) -L$(PRODLIBHOME)  
BOOTSTRAPLIB=/tmp/bootstraplib/
SHLIB_MAP=-bE:$(PRODDEFHOME)$(_LIBNAME).$(DEF_EXT)
SHLIB_NAME=
SHLIB_OBJS=-bexpall $($*SOLIBS) $(_LIBDIR)$(_LIBNAME).$(LIB_EXT) -bI:$(PRODDEFHOME)$(_LIBNAME).$(IMP_EXT) -L/usr/lib -lm -lc -lpthreads  
SHLIB_OBJS_OLD=
SHLIB_OTHER=$(_LIBNAME_LIBS) $(_VAR_LIBS)
SHLIB_BOOTSTRAP_OTHER=$(_LIBNAME_EXTRALIBS) $(_VAR_EXTRALIBS)
SHLIB_CLOSED=
SHLIB_RP=

LD_SHLIB_COMMAND=$(LD) -L$(ORACLE_HOME)/lib -o $@ $($*SOLIBS) $(PRODLIBHOME)$*.$(LIB_EXT) -bE:$(PRODDEFHOME)$*.$(DEF_EXT) -bI:$(PRODDEFHOME)$*.$(IMP_EXT) -bM:SRE -bnoentry -L/usr/lib -lm -lc -lpthreads $(SHLIB_OTHER_DEP)

DLOPENLIB_COMMAND=$(LD_SHLIB_COMMAND) $(PROD_DLLIBS) $($*LIBS)

NEW_LD_SHLIB_COMMAND=$(SHLIB_LD) $(SHLIB_MAP) $(SHLIB_NAME) $(SHLIB_OBJS) \
$(SHLIB_RP) $(SHLIB_OTHER) $(SHLIB_CLOSED)
NEW_DLOPENLIB_COMMAND=$(NEW_LD_SHLIB_COMMAND)
BOOTSTRAPLIB_COMMAND=$(NEW_LD_SHLIB_COMMAND) $(SHLIB_BOOTSTRAP_OTHER)
NEW_LD_SHLIB_DEP=$(PRODDEFHOME)%.$(DEF_EXT) $(PRODLIBHOME)%.$(LIB_EXT) $(PRODDEFHOME)%.$(IMP_EXT) 
NEW_DLOPENLIB_DEP=$(NEW_LD_SHLIB_DEP)
BOOTSTRAPLIB_DEP=$(NEW_LD_SHLIB_DEP)

LINKSHLIB=$(BINHOME)linkshlib
LINKSHLIB_CALL=$(LINKSHLIB) $@ $(MAKEFILE) $(SO_EXT)
CUS_NEW_SHLIB_COMMAND=$(LINKSHLIB_CALL) new_ld_shlib $(VAR)
CUS_NEW_DLOPENLIB_COMMAND=$(LINKSHLIB_CALL) new_dlopenlib $(VAR)
CUS_SHLIB_COMMAND=$(LINKSHLIB_CALL) ld_shlib $(VAR)
CUS_DLOPENLIB_COMMAND=$(LINKSHLIB_CALL) dlopenlib $(VAR)
CUS_VARLIB_COMMAND=$(LINKSHLIB_CALL) var $(PRODHOME)admin
CUS_BOOTSTRAPLIB_COMMAND=$(LINKSHLIB_CALL) bootstrap

FOLLOW=
NOLEAF=

TTLIBS=$(NAETTOBJS) $(STATICTTLIBS) $(LLIBPLS) $(LLIBSQL) $(LLIBXSD) $(AIXIMP)

LINKLDLIBS=$(LDLIBS) $(AIXIMP)
LINKTTLIBS=$(ORACLETTLIBS) $(LINKLDLIBS) $(LLIBSQL) $(LLIBXSD) $(NAETTOBJS)
SUIDLINKLDLIBS=$(LINKLDLIBS)

UNIQ=uniq

ORACLUSTERDIR=$(ORACLE_HOME)/$(LIBDIR)/

LIBTTSHNAME=ttsh11
LIBTTSH=$(LIBHOME)$(LIB_PREFIX)$(LIBTTSHNAME).$(SO_EXT)
LIBTTSH_EXP_FILE=$(ORACLE_HOME)/lib/ttsh.lst
LIBTTSH_SHR_OBJ_NAME=$(SHROBJ_PREFIX)$(LIBTTSHNAME).$(OBJ_EXT)
LLIBTTSH=$(LDLIBFLAG)$(LIBTTSHNAME)
LINKTTSH=$(LLIBTTSH) $(LDLIBS)



LD_COMMAND=/bin/ld
GEN_SHRAR_IMP=$(BINHOME)gen_shrar_imp.sh
SHRAR_EXT=shrar
STATIC_PREFIX=st
STATIC_SUFFIX=st
SHROBJ_PREFIX=shr_


SHRAR_DEST_DIR=$(PRODLIBHOME)

SHRAR_IMP_FILE=$(PRODDEFHOME)$(LIB_PREFIX)$*.$(IMP_EXT)

SHROBJ_NAME=$(SHRAR_DEST_DIR)/$(SHROBJ_PREFIX)$*.$(OBJ_EXT)
SHR_AR_NAME=$(SHRAR_DEST_DIR)$(LIB_PREFIX)$*.$(LIB_EXT)
SHR_SO_NAME=$(SHRAR_DEST_DIR)$(LIB_PREFIX)$*.$(SO_EXT)

LD_SHRAR_LIB_DEP=$(SHRAR_DEST_DIR)$(LIB_PREFIX)$(STATIC_PREFIX)%.$(LIB_EXT)

DEF_SHRAR_COMMAND=$(GREP) -v ' U '  $(SHRAR_DEST_DIR)$(LIB_PREFIX)$*.$(NM_EXT) | $(GREP) -v "::" | $(GREP) -v "(" |$(GREP) -v "\.cc" | $(AWK) '{print $$3}' | $(SED) -e "s/\.//g" | $(GREP) -v "^_"| $(SORT) | $(UNIQ) > $(PRODDEFHOME)$(LIB_PREFIX)$*.$(DEF_EXT)

IMP_SHRAR_COMMAND=$(GEN_SHRAR_IMP) $(SHRAR_DEST_DIR)$(LIB_PREFIX)$(STATIC_PREFIX)$*.$(LIB_EXT) $(PRODDEFHOME)$(LIB_PREFIX)$*.$(IMP_EXT) EXPLIST_IMP_LIBS="$(EXPLIST_IMP_LIBS)" ST_AR_IMP_LIBS="$(ST_AR_IMP_LIBS)"

IMP_SHRSO_COMMAND=$(GEN_SHRAR_IMP) $(SHRAR_DEST_DIR)$(LIB_PREFIX)$(STATIC_PREFIX)$*.$(LIB_EXT) $(PRODDEFHOME)$(LIB_PREFIX)$*.$(IMP_EXT) EXPLIST_IMP_LIBS="$(EXPLIST_IMP_LIBS)" ST_AR_IMP_LIBS="$(ST_AR_IMP_LIBS)" SO_AR

LD_SHRAR_LIB_COMMAND=$(LD_COMMAND) $(SHROBJ_MODE) -G -L$(ORACLE_HOME)/lib -o $(SHROBJ_NAME) $(SHRAR_DEST_DIR)$(LIB_PREFIX)$(STATIC_PREFIX)$*.$(LIB_EXT) $($*SOLIBS) -bE:$(PRODDEFHOME)$(LIB_PREFIX)$*.$(DEF_EXT) -bI:$(SHRAR_IMP_FILE) -bM:SRE -bnoentry -L/usr/lib -lm -lc -lpthreads $(SHLIB_OTHER_DEP) $(PROD_DLLIBS) $($*LIBS)

shrar_soobj_%:

	$(SILENT)$(ADE_DEL_FILE)
	$(NM) $(NMFLAGS) $(SHRAR_DEST_DIR)$(LIB_PREFIX)$(STATIC_PREFIX)$*.$(LIB_EXT) > $(SHRAR_DEST_DIR)$(LIB_PREFIX)$*.$(NM_EXT)
	$(DEF_SHRAR_COMMAND)
	$(IMP_SHRSO_COMMAND)
	$(LD_SHRAR_LIB_COMMAND)
	$(RMF) $(SHRAR_DEST_DIR)$(LIB_PREFIX)$*.$(NM_EXT)

shrobj_%:

	$(SILENT)$(ADE_DEL_FILE)
	$(NM) $(NMFLAGS) $(SHRAR_DEST_DIR)$(LIB_PREFIX)$(STATIC_PREFIX)$*.$(LIB_EXT) > $(SHRAR_DEST_DIR)$(LIB_PREFIX)$*.$(NM_EXT)
	$(DEF_SHRAR_COMMAND)
	$(IMP_SHRAR_COMMAND)
	$(LD_SHRAR_LIB_COMMAND)
	$(RMF) $(SHRAR_DEST_DIR)$(LIB_PREFIX)$*.$(NM_EXT)

shrar_%: shrobj_%
	$(ARCREATE) $(SHR_AR_NAME) $(SHROBJ_NAME)
	$(RMF) $(SHROBJ_NAME)
	$(SYM_COMMAND)

shr_so_%: shrobj_%
	$(MV) $(SHROBJ_NAME) $(SHR_SO_NAME)
	$(SYM_COMMAND)

shrarso_%: shrar_soobj_%
	$(MV) $(SHROBJ_NAME) $(SHR_SO_NAME)
	$(SYM_COMMAND)

WORDSIZE=64

# Exiting /ade/b/1663622200/oracle/buildtools/mkfile/platform.mk
# Entering /ade/b/1663622200/oracle/buildtools/mkfile/rules.mk
 
# Exiting /ade/b/1663622200/oracle/buildtools/mkfile/rules.mk
# Exiting /ade/b/1663622200/oracle/buildtools/mkfile/prefix.mk
# Entering /ade/b/1663622200/oracle/ldap/exports.mk

# Entering /ade/b/1663622200/oracle/ldap/iasr_exports.mk


# Exiting /ade/b/1663622200/oracle/ldap/iasr_exports.mk

LDAP_VERSION=11

LIBGSLSSFNAME= gslssf$(LDAP_VERSION)
LLIBGSLSSF= $(LDLIBFLAG)$(LIBGSLSSFNAME)$(LIB_SUFFIX)
LIBGSLSSF= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLSSFNAME).$(LIB_EXT)

LIBGSLSSBNAME= gslssb$(LDAP_VERSION)
LLIBGSLSSB= $(LDLIBFLAG)$(LIBGSLSSBNAME)$(LIB_SUFFIX)
LIBGSLSSB= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLSSBNAME).$(LIB_EXT)

LIBGSLBER_SNAME= gslber_s$(LDAP_VERSION)
LLIBGSLBER_S= $(LDLIBFLAG)$(LIBGSLBER_SNAME)$(LIB_SUFFIX)
LIBGSLBER_S= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLBER_SNAME).$(LIB_EXT)

LIBGSLAVLNAME= gslavl$(LDAP_VERSION)
LLIBGSLAVL= $(LDLIBFLAG)$(LIBGSLAVLNAME)$(LIB_SUFFIX)
LIBGSLAVL= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLAVLNAME).$(LIB_EXT)

LIBGSLRNAME= gslr$(LDAP_VERSION)
LLIBGSLR= $(LDLIBFLAG)$(LIBGSLRNAME)$(LIB_SUFFIX)
LIBGSLR= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLRNAME).$(LIB_EXT)

LIBGSLRTANAME= gslrta$(LDAP_VERSION)
LLIBGSLRTA= $(LDLIBFLAG)$(LIBGSLRTANAME)$(LIB_SUFFIX)
LIBGSLRTA= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLRTANAME).$(LIB_EXT)

LIBGSLRTDNAME= gslrtd$(LDAP_VERSION)
LLIBGSLRTD= $(LDLIBFLAG)$(LIBGSLRTDNAME)$(LIB_SUFFIX)
LIBGSLRTD= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLRTDNAME).$(LIB_EXT)

LIBGSLRTMNAME= gslrtm$(LDAP_VERSION)
LLIBGSLRTM= $(LDLIBFLAG)$(LIBGSLRTMNAME)$(LIB_SUFFIX)
LIBGSLRTM= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLRTMNAME).$(LIB_EXT)

LIBGSLRTPNAME= gslrtp$(LDAP_VERSION)
LLIBGSLRTP= $(LDLIBFLAG)$(LIBGSLRTPNAME)$(LIB_SUFFIX)
LIBGSLRTP= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLRTPNAME).$(LIB_EXT)

LIBGSLRTRNAME= gslrtr$(LDAP_VERSION)
LLIBGSLRTR= $(LDLIBFLAG)$(LIBGSLRTRNAME)$(LIB_SUFFIX)
LIBGSLRTR= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLRTRNAME).$(LIB_EXT)

LIBGSLRTUNAME= gslrtu$(LDAP_VERSION)
LLIBGSLRTU= $(LDLIBFLAG)$(LIBGSLRTUNAME)$(LIB_SUFFIX)
LIBGSLRTU= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLRTUNAME).$(LIB_EXT)

LIBGSLDBNAME= gsldb$(LDAP_VERSION)
LLIBGSLDB= $(LDLIBFLAG)$(LIBGSLDBNAME)$(LIB_SUFFIX)
LIBGSLDB= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLDBNAME).$(LIB_EXT)


LIBGSLUSNAME= gslus$(LDAP_VERSION)
LLIBGSLUS= $(LDLIBFLAG)$(LIBGSLUSNAME)$(LIB_SUFFIX)
LIBGSLUS= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLUSNAME).$(LIB_EXT)

LIBGSLTNAME= gslt$(LDAP_VERSION)
LLIBGSLT= $(LDLIBFLAG)$(LIBGSLTNAME)$(LIB_SUFFIX)
LIBGSLT= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLTNAME).$(LIB_EXT)

LIBGSLSGNAME= gslsg$(LDAP_VERSION)
LLIBGSLSG= $(LDLIBFLAG)$(LIBGSLSGNAME)$(LIB_SUFFIX)
LIBGSLSG= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLSGNAME).$(LIB_EXT)

LIBGSLECNAME= gslec$(LDAP_VERSION)
LLIBGSLEC= $(LDLIBFLAG)$(LIBGSLECNAME)$(LIB_SUFFIX)
LIBGSLEC= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLECNAME).$(LIB_EXT)

LIBGSLSMNAME= gslsm$(LDAP_VERSION)
LLIBGSLSM= $(LDLIBFLAG)$(LIBGSLSMNAME)$(LIB_SUFFIX)
LIBGSLSM= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLSMNAME).$(LIB_EXT)

LIBGSLIRNAME= gslir$(LDAP_VERSION)
LLIBGSLIR= $(LDLIBFLAG)$(LIBGSLIRNAME)$(LIB_SUFFIX)
LIBGSLIR= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLIRNAME).$(LIB_EXT)

LIBGSLGRNAME= gslgr$(LDAP_VERSION)
LLIBGSLGR= $(LDLIBFLAG)$(LIBGSLGRNAME)$(LIB_SUFFIX)
LIBGSLGR= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLGRNAME).$(LIB_EXT)

LIBGSLAUDNAME= gslaud$(LDAP_VERSION)
LLIBGSLAUD= $(LDLIBFLAG)$(LIBGSLAUDNAME)$(LIB_SUFFIX)
LIBGSLAUD= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLAUDNAME).$(LIB_EXT)

LIBGSLPLNAME= gslpl$(LDAP_VERSION)
LLIBGSLPL= $(LDLIBFLAG)$(LIBGSLPLNAME)$(LIB_SUFFIX)
LIBGSLPL= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLPLNAME).$(LIB_EXT)

LIBGSLMNAME= gslm$(LDAP_VERSION)
LLIBGSLM= $(LDLIBFLAG)$(LIBGSLMNAME)$(LIB_SUFFIX)
LIBGSLM=$(LIBHOME)$(LIB_PREFIX)$(LIBGSLMNAME).$(LIB_EXT)

LIBSGSL_SNAME= sgsl_s$(LDAP_VERSION)
LLIBSGSL_S= $(LDLIBFLAG)$(LIBSGSL_SNAME)$(LIB_SUFFIX)
LIBSGSL_S= $(LIBHOME)$(LIB_PREFIX)$(LIBSGSL_SNAME).$(LIB_EXT)

LIBLDAPCLNTNAME= ldapclnt$(LDAP_VERSION)
LIBLDAPCLNT= $(LIBHOME)$(LIB_PREFIX)$(LIBLDAPCLNTNAME).$(LIB_EXT)
LLIBLDAPCLNT= $(LDLIBFLAG)$(LIBLDAPCLNTNAME)

LIBLDAPCLNTSHNAME= ldapclntsh$(LDAP_VERSION)
LIBLDAPCLNTSH= $(LIBHOME)$(LIB_PREFIX)$(LIBLDAPCLNTSHNAME).$(LIB_EXT)
LLIBLDAPCLNTSH= $(LDLIBFLAG)$(LIBLDAPCLNTSHNAME)
LIBLDAPCLNTSHLIBS= $(LIBLDAPCLNTSHNAME)LIBS

LIBLDAPJCLNTNAME= ldapjclnt$(LDAP_VERSION)
LIBLDAPJCLNT= $(LIBHOME)$(LIB_PREFIX)$(LIBLDAPJCLNTNAME).$(LIB_EXT)
LIBLDAPJCLNTSH = $(LIBHOME)$(LIB_PREFIX)$(LIBLDAPJCLNTNAME).$(SO_EXT)
LLIBLDAPJCLNT= $(LDLIBFLAG)$(LIBLDAPJCLNTNAME)
LIBLDAPJCLNTLIBS= $(LIBLDAPJCLNTNAME)LIBS

LIBGSLMTNAME= gslmt$(LDAP_VERSION)
LLIBGSLMT= $(LDLIBFLAG)$(LIBGSLMTNAME)$(LIB_SUFFIX)
LIBGSLMT= $(LIBHOME)$(LIB_PREFIX)$(LIBGSLMTNAME).$(LIB_EXT)

LIBZTKGNAME= ztkg$(LDAP_VERSION)
LIBZTKG= $(LIBHOME)$(LIB_PREFIX)$(LIBZTKGNAME).$(LIB_EXT)
LLIBZTKG= $(LDLIBFLAG)$(ILIB_PREFIX)$(LIBZTKGNAME)$(ILIB_SUFFIX)

LDAPHOME=    $(ORACLE_HOME)/ldap/
LDAPBIN=     $(LDAPHOME)$(BINDIR)/
LDAPLIB=     $(LDAPHOME)$(LIBDIR)/
LDAPJLIB=    $(LDAPHOME)jlib/

LDAPPUBH=    $(I_SYM)$(LDAPHOME)public $(I_SYM)$(LDAPHOME)include

SSLPUBH = $(I_SYM)$(LDAPHOME)public/sslinc $(I_SYM)$(LDAPHOME)include/sslinc

LIBNZFNAME= nnzf$(LDAP_VERSION)
LLIBNZF= $(LDLIBFLAG)$(ILIB_PREFIX)$(LIBNZFNAME)$(ILIB_SUFFIX)
LIBNZF=$(LIBHOME)$(LIB_PREFIX)$(LIBNZFNAME).$(LIB_EXT)
 
NZNAME= nnz$(LDAP_VERSION)
LLIBNZ= $(LDLIBFLAG)$(ILIB_PREFIX)$(NZNAME)$(ILIB_SUFFIX)
LIBNZ=$(LIBHOME)$(LIB_PREFIX)$(NZNAME).$(SO_EXT)

OWMNAME = owm2
LIBOWM  = $(LDAPLIB)$(LIB_PREFIX)$(OWMNAME).$(SO_EXT)

NZJSNAME = nzjs${LDAP_VERSION}
LLIBNZJS = $(LDLIBFLAG)$(ILIB_PREFIX)$(NZJSNAME)$(ILIB_SUFFIX)
LIBNZJS  = $(LDAPLIB)$(LIB_PREFIX)$(NZJSNAME).$(LIB_EXT)


SSLBNAME = nsslb${LDAP_VERSION}
LIBSSLB  = $(LIBHOME)$(LIB_PREFIX)$(SSLBNAME).$(LIB_EXT)
LLIBSSLB = $(LDLIBFLAG)$(ILIB_PREFIX)$(SSLBNAME)$(ILIB_SUFFIX)
LIBSSLB  = $(LDAPLIB)$(LIB_PREFIX)$(SSLBNAME).$(LIB_EXT)

LIBZTNAME  = zt${LDAP_VERSION}
ZTRNAME = ztr${LDAP_VERSION}
LIBZT   = $(LIBHOME)$(LIB_PREFIX)$(LIBZTNAME).$(LIB_EXT)
LLIBZT   = $(LDLIBFLAG)$(ILIB_PREFIX)$(LIBZTNAME)$(ILIB_SUFFIX)
LIBZTR  = $(LIBHOME)$(LIB_PREFIX)$(ZTRNAME).$(LIB_EXT)
LOC_LIBZTR   = $(LDAPLIB)$(LIB_PREFIX)$(ZTRNAME).$(LIB_EXT)
LOC_LIBNZ  = $(LDAPLIB)$(LIB_PREFIX)$(NZNAME).$(LIB_EXT)
LIBZTLWNAME  = ztlw${LDAP_VERSION}
LIBZTLW   = $(LIBHOME)$(LIB_PREFIX)$(LIBZTLWNAME).$(LIB_EXT)
LLIBZTLW   = $(LDLIBFLAG)$(ILIB_PREFIX)$(LIBZTLWNAME)$(ILIB_SUFFIX)

NZLIBS = $(LLIBNZ) $(LLIBZT) $(LLIBZTKG)
NZLIBSLW = $(LLIBNZ) $(LLIBZTLW)

SPFLAGS+= -DLDAP_CM

# Entering /ade/b/1663622200/oracle/ldap/s_exports.mk

NZLIBS = $(LLIBNZ) $(LLIBZT) $(LLIBZTKG)

# Exiting /ade/b/1663622200/oracle/ldap/s_exports.mk
# Exiting /ade/b/1663622200/oracle/ldap/exports.mk
# Entering /ade/b/1663622200/oracle/encryption/exports.mk

ENCRYPTIONHOME  = $(ORACLE_HOME)/encryption/
ENCRYPTIONLIB   = $(ENCRYPTIONHOME)$(LIBDIR)/
ENCRYPTIONJLIB  = $(ENCRYPTIONHOME)jlib/
ENCRYPTIONPUBH  = $(I_SYM)$(ENCRYPTIONHOME)include

ENCRYPTION_VERSION=11
BASENAME        =n
CRYPTNAME       =${BASENAME}crypt$(ENCRYPTION_VERSION)
LIBSNS          =$(ENCRYPTIONLIB)$(LIB_PREFIX)$(CRYPTNAME).$(LIB_EXT)
LLIBNCRYPT      =$(LDLIBFLAG)$(ILIB_PREFIX)$(CRYPTNAME)$(ILIB_SUFFIX)

PHAOSJAR=$(ENCRYPTIONJLIB)ojpse.$(JAR_EXT)
PHAOSCMSJAR=$(ENCRYPTIONJLIB)ojpcms.$(JAR_EXT)
CRYPTSHNAME=$(BASENAME)cryptsh$(ENCRYPTION_VERSION)
LLIBNCRYPTSH=$(LDLIBFLAG)$(CRYPTSHNAME)$(ILIB_SUFFIX)
# Entering /ade/b/1663622200/oracle/encryption/s_exports.mk

# Exiting /ade/b/1663622200/oracle/encryption/s_exports.mk
# Exiting /ade/b/1663622200/oracle/encryption/exports.mk
# Entering /ade/b/1663622200/oracle/network/exports.mk

NETWORKHOME=$(ORACLE_HOME)/network/
NETWORKADMIN=$(NETWORKHOME)admin/
NETWORKINSTALL=$(NETWORKHOME)install/
NETWORKDEMO=$(NETWORKHOME)demo/

# Entering /ade/b/1663622200/oracle/network/adapters.mk

# Entering /ade/b/1663622200/oracle/network/s_adapters.mk

# Exiting /ade/b/1663622200/oracle/network/s_adapters.mk

# Entering /ade/b/1663622200/oracle/network/libnames.mk

NETWORK_VERSION=11
BASENAME=n
NETWORKLIB=$(NETWORKHOME)$(LIBDIR)/
NETWORKJLIB=$(NETWORKHOME)$(JLIBDIR)/

COMMONNAME=${BASENAME}${NETWORK_VERSION}
NLNAME=${BASENAME}l${NETWORK_VERSION}
TCPNAME=${BASENAME}tcp${NETWORK_VERSION}
QUENAME=${BASENAME}que${NETWORK_VERSION}
DECNETNAME=${BASENAME}dec${NETWORK_VERSION}
LU62NAME=${BASENAME}lu62${NETWORK_VERSION}
MBNAME=${BASENAME}mb${NETWORK_VERSION}
DCENAME=${BASENAME}dce${NETWORK_VERSION}
BEQNAME=${BASENAME}beq${NETWORK_VERSION}
IPCNAME=${BASENAME}ipc${NETWORK_VERSION}
SPXNAME=${BASENAME}spx${NETWORK_VERSION}
TLINAME=${BASENAME}tli${NETWORK_VERSION}
TLITNAME=${BASENAME}tlit${NETWORK_VERSION}
TLISNAME=${BASENAME}tlis${NETWORK_VERSION}
TLIDNAME=${BASENAME}tlid${NETWORK_VERSION}
USNAME=${BASENAME}us${NETWORK_VERSION}
SHMNAME=${BASENAME}shm${NETWORK_VERSION}
TCPSNAME=${BASENAME}tcps${NETWORK_VERSION}
TCPAIONAME=${BASENAME}tcpaio${NETWORK_VERSION}
ENTRUSTNAME=${BASENAME}nzentr${NETWORK_VERSION}
NSGRNAME=${BASENAME}sgr${NETWORK_VERSION}
LSNRNAME=${BASENAME}lsnr${NETWORK_VERSION}
LSNRCNAME=${BASENAME}lsnrc${NETWORK_VERSION}
ONNAME=${BASENAME}on${NETWORK_VERSION}
ONDNAME=${BASENAME}ond${NETWORK_VERSION}
ONCNAME=${BASENAME}onc${NETWORK_VERSION}
ONCJNAME=${BASENAME}oncj${NETWORK_VERSION}
RONAME=${BASENAME}ro${NETWORK_VERSION}
ROCNAME=${BASENAME}roc${NETWORK_VERSION}
ROXNAME=${BASENAME}rox${NETWORK_VERSION}
ROTNAME=${BASENAME}rot${NETWORK_VERSION}
CMNAME=${BASENAME}cm${NETWORK_VERSION}
NHOSTNAME=${BASENAME}host${NETWORK_VERSION}
TNSNAME=${BASENAME}tns${NETWORK_VERSION}
ORACLENAME=${BASENAME}oname${NETWORK_VERSION}
NISNAME=${BASENAME}nis${NETWORK_VERSION}
CDSNAME=${BASENAME}cds${NETWORK_VERSION}
NDSNAME=${BASENAME}nds${NETWORK_VERSION}
LDAPNAME=${BASENAME}ldap${NETWORK_VERSION}
LDAPJNAME=${BASENAME}ldapj${NETWORK_VERSION}
NUJNINAME=${BASENAME}jni${NETWORK_VERSION}
NZJSNAME=${BASENAME}zjs${NETWORK_VERSION}
JSSLNAME=${BASENAME}jssl${NETWORK_VERSION}

NMPNAME=${BASENAME}nmp${NETWORK_VERSION}

TANAME=${BASENAME}ta${NETWORK_VERSION}
TALNAME=${BASENAME}tal${NETWORK_VERSION}


SNLPTDUM         =  $(NETWORKLIB)snlptdum.$(OBJ_EXT) 
OSNTABST         = $(NETWORKLIB)osntabst.$(OBJ_EXT)
NNFGT            = $(NETWORKLIB)nnfgt.$(OBJ_EXT)

LIBNETWORK	 =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBTHINNCR       =  $(NETWORKLIB)$(LIB_PREFIX)$(ROTNAME).$(LIB_EXT)

LOC_LIBNUJNI     =  $(NETWORKLIB)$(LIB_PREFIX)$(NUJNINAME).$(LIB_EXT)
LOC_LIBJSSL      =  $(NETWORKLIB)$(LIB_PREFIX)$(JSSLNAME).$(LIB_EXT)
LIBONCJ          =  $(NETWORKLIB)$(LIB_PREFIX)$(ONCJNAME).$(SO_EXT)
LIBNUJNI         =  $(NETWORKLIB)$(LIB_PREFIX)$(NUJNINAME).$(SO_EXT)
LIBJSSL          =  $(NETWORKLIB)$(LIB_PREFIX)$(JSSLNAME).$(SO_EXT)
LIBLDAPJ         =  $(NETWORKLIB)$(LIB_PREFIX)$(LDAPJNAME).$(SO_EXT)
LOC_LIBONCJ      =  $(NETWORKLIB)$(LIB_PREFIX)$(ONCJNAME).$(LIB_EXT)
LOC_LIBLDAPJ     =  $(NETWORKLIB)$(LIB_PREFIX)$(LDAPJNAME).$(LIB_EXT)

LIBNCR           =  $(NETWORKLIB)$(LIB_PREFIX)$(RONAME).$(LIB_EXT)
LIBNFP           =  $(NETWORKLIB)$(LIB_PREFIX)$(CMNAME).$(LIB_EXT)
LIBNI            =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNNCC          =  $(NETWORKLIB)$(LIB_PREFIX)$(ONCNAME).$(LIB_EXT)
LIBNND           =  $(NETWORKLIB)$(LIB_PREFIX)$(ONDNAME).$(LIB_EXT)
LIBNNO           =  $(NETWORKLIB)$(LIB_PREFIX)$(ONNAME).$(LIB_EXT)
LIBNSGR          =  $(NETWORKLIB)$(LIB_PREFIX)$(NSGRNAME).$(LIB_EXT)
LIBNSGL          =  $(NETWORKLIB)$(LIB_PREFIX)$(LSNRNAME).$(LIB_EXT)
LIBNSGLC         =  $(NETWORKLIB)$(LIB_PREFIX)$(LSNRCNAME).$(LIB_EXT)

LLIBNCR           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(RONAME)$(ILIB_SUFFIX)
LLIBNFP           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(CMNAME)$(ILIB_SUFFIX)
LLIBNI            =  $(LDLIBFLAG)$(ILIB_PREFIX)$(COMMONNAME)$(ILIB_SUFFIX)
LLIBNNCC          =  $(LDLIBFLAG)$(ILIB_PREFIX)$(ONCNAME)$(ILIB_SUFFIX)
LLIBNND           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(ONDNAME)$(ILIB_SUFFIX)
LLIBNNO           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(ONNAME)$(ILIB_SUFFIX)
LLIBNSGR          =  $(LDLIBFLAG)$(ILIB_PREFIX)$(NSGRNAME)$(ILIB_SUFFIX)
LLIBNSGL          =  $(LDLIBFLAG)$(ILIB_PREFIX)$(LSNRNAME)$(ILIB_SUFFIX)
LLIBNSGLC         =  $(LDLIBFLAG)$(ILIB_PREFIX)$(LSNRCNAME)$(ILIB_SUFFIX)


LIBNTT           =  $(NETWORKLIB)$(LIB_PREFIX)$(TCPNAME).$(LIB_EXT)
LIBNTTAIO        =  $(NETWORKLIB)$(LIB_PREFIX)$(TCPAIONAME).$(SO_EXT)
LOC_LIBNTTAIO    =  $(NETWORKLIB)$(LIB_PREFIX)$(TCPAIONAME).$(LIB_EXT)
LOC_LIBNTVI      =  $(NETWORKLIB)$(LIB_PREFIX)$(VINAME).$(LIB_EXT)
LIBNTVI          =  $(NETWORKLIB)$(LIB_PREFIX)$(VINAME).$(SO_EXT)
LOC_LIBNTEVQ     =  $(NETWORKLIB)$(LIB_PREFIX)$(QUENAME).$(LIB_EXT)
LIBNTEVQ         =  $(NETWORKLIB)$(LIB_PREFIX)$(QUENAME).$(SO_EXT)
LIBNTZ           =  $(NETWORKLIB)$(LIB_PREFIX)$(TCPSNAME).$(LIB_EXT)
LIBNTZSTUB       =  $(NETWORKLIB)$(LIB_PREFIX)$(TCPSNAME)_std.$(LIB_EXT)
LOC_LIBNZTWVE    =  $(NETWORKLIB)$(LIB_PREFIX)$(ENTRUSTNAME).$(LIB_EXT)
LIBNZTWVE        =  $(NETWORKLIB)$(LIB_PREFIX)$(ENTRUSTNAME).$(SO_EXT)
LIBNTS           =  $(NETWORKLIB)$(LIB_PREFIX)$(SPXNAME).$(LIB_EXT)
LIBNTD           =  $(NETWORKLIB)$(LIB_PREFIX)$(DECNETNAME).$(LIB_EXT)
LIBNTOD          =  $(NETWORKLIB)$(LIB_PREFIX)$(DCENAME).$(LIB_EXT)
LIBCDS           =  $(NETWORKLIB)$(LIB_PREFIX)$(CDSNAME).$(LIB_EXT)
LIBNTLU62        =  $(NETWORKLIB)$(LIB_PREFIX)$(LU62NAME).$(LIB_EXT)
LIBNTTLI	 =  $(NETWORKLIB)$(LIB_PREFIX)$(TLINAME).$(LIB_EXT)
LIBNTUS          =  $(NETWORKLIB)$(LIB_PREFIX)$(USNAME).$(LIB_EXT)
LIBNTSHM         =  $(NETWORKLIB)$(LIB_PREFIX)$(SHMNAME).$(LIB_EXT)
LIBNTP           =  $(NETWORKLIB)$(LIB_PREFIX)$(BEQNAME).$(LIB_EXT)
LIBNTNP          =  $(NETWORKLIB)$(LIB_PREFIX)$(NMPNAME).$(LIB_EXT)

LLIBNTT           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(TCPNAME)$(ILIB_SUFFIX)
LLIBNTVI          =  $(LDLIBFLAG)$(ILIB_PREFIX)$(VINAME)$(ILIB_SUFFIX)
LLIBNTEVQ         =  $(LDLIBFLAG)$(ILIB_PREFIX)$(QUENAME).$(ILIB_SUFFIX)
LLIBNTZ           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(TCPSNAME)$(ILIB_SUFFIX)
LLIBNTS           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(SPXNAME)$(ILIB_SUFFIX)
LLIBNTD           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(DECNETNAME)$(ILIB_SUFFIX)
LLIBNTOD          =  $(LDLIBFLAG)$(ILIB_PREFIX)$(DCENAME)$(ILIB_SUFFIX)
LLIBCDS           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(CDSNAME)$(ILIB_SUFFIX)
LLIBNTLU62        =  $(LDLIBFLAG)$(ILIB_PREFIX)$(LU62NAME)$(ILIB_SUFFIX)
LLIBNTTLI	 =  $(LDLIBFLAG)$(ILIB_PREFIX)$(TLINAME)$(ILIB_SUFFIX)
LLIBNTUS          =  $(LDLIBFLAG)$(ILIB_PREFIX)$(USNAME)$(ILIB_SUFFIX)
LLIBNTSHM        = $(NETWORKLIB)$(LIB_PREFIX)$(SHMNAME)$(ILIB_SUFFIX)
LLIBNTP           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(BEQNAME)$(ILIB_SUFFIX)
LLIBNTNP          =  $(LDLIBFLAG)$(ILIB_PREFIX)$(NMPNAME)$(ILIB_SUFFIX)

LIBNL1           =  $(NETWORKLIB)$(LIB_PREFIX)$(NLNAME).$(LIB_EXT)
LIBNL2           =  $(NETWORKLIB)$(LIB_PREFIX)$(NLNAME).$(LIB_EXT)

LIBNL            =  $(NETWORKLIB)$(LIB_PREFIX)$(NLNAME).$(LIB_EXT)
LLIBNL           =  $(LDLIBFLAG)$(ILIB_PREFIX)$(NLNAME)$(ILIB_SUFFIX)


LIBNUAPI         =  $(NETWORKLIB)$(LIB_PREFIX)$(TANAME).$(LIB_EXT)
LIBNULOCAL       =  $(NETWORKLIB)$(LIB_PREFIX)$(TALNAME).$(LIB_EXT)

LLIBNUAPI         =  $(LDLIBFLAG)$(ILIB_PREFIX)$(TANAME)$(ILIB_SUFFIX)
LLIBNULOCAL       =  $(LDLIBFLAG)$(ILIB_PREFIX)$(TALNAME)$(ILIB_SUFFIX)


LLIBNUAPI	 = $(LDLIBFLAG)$(ILIB_PREFIX)$(TANAME)$(ILIB_SUFFIX)
LLIBNULOCAL	 = $(LDLIBFLAG)$(ILIB_PREFIX)$(TALNAME)$(ILIB_SUFFIX)
LLIBSSL          = #$(LDLIBFLAG)$(ILIB_PREFIX)sslref-bsafe$(ILIB_SUFFIX)
LLIBNZJS 	 = $(LDLIBFLAG)$(ILIB_PREFIX)$(NZJSNAME)$(ILIB_SUFFIX)

LIBNA            =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNAE           =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNAU           =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNMP           =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNNCI          =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNNFG          =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNNG           =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNPL           =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNR            =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNS            =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNT            =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNTR           =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBNMS0          =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBSSLREF 	 =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LIBZT            =  $(NETWORKLIB)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)


LIBNZJS          =  $(NETWORKLIB)$(LIB_PREFIX)$(NZJSNAME).$(LIB_EXT)

LIBNLNV          =  $(NETWORKLIB)$(LIB_PREFIX)$(NLNAME).$(LIB_EXT)

LDAPSYSLIBD = $(LIBHOME)$(LIB_PREFIX)$(LIBLDAPCLNTNAME).$(LIB_EXT)
LDAPSYSLIBS = $(LDLIBFLAG)$(ILIB_PREFIX)$(LIBLDAPCLNTNAME)$(ILIB_SUFFIX)

COMMONSHNAME=$(BASENAME)sh$(NETWORK_VERSION)
NLSHNAME=$(BASENAME)lsh$(NETWORK_VERSION)
LDAPSHNAME=$(BASENAME)ldapsh$(NETWORK_VERSION)
ROSHNAME=$(BASENAME)rosh$(NETWORK_VERSION)
LIBNETWORKSH=$(NETWORKLIB)$(LIB_PREFIX)$(COMMONSHNAME).$(SO_EXT)
LIBNLSH=$(NETWORKLIB)$(LIB_PREFIX)$(NLSHNAME).$(SO_EXT)
LIBLDAPSH=$(NETWORKLIB)$(LIB_PREFIX)$(LDAPSHNAME).$(SO_EXT)
LIBRPCSH=$(NETWORKLIB)$(LIB_PREFIX)$(ROSHNAME).$(SO_EXT)
LLIBNETWORKSH=$(LDLIBFLAG)$(COMMONSHNAME)$(ILIB_SUFFIX)
LLIBNLSH=$(LDLIBFLAG)$(NLSHNAME)$(ILIB_SUFFIX)
LLIBLDAPSH=$(LDLIBFLAG)$(LDAPSHNAME)$(ILIB_SUFFIX)
LLIBRPCSH=$(LDLIBFLAG)$(ROSHNAME)$(ILIB_SUFFIX)
# Exiting /ade/b/1663622200/oracle/network/libnames.mk

# Exiting /ade/b/1663622200/oracle/network/adapters.mk

LIBNTTCP     = $(LIBHOME)$(LIB_PREFIX)$(TCPNAME).$(LIB_EXT)
LLIBNTTCP    = $(LDLIBFLAG)$(ILIB_PREFIX)$(TCPNAME)$(ILIB_SUFFIX)

LIBNTOD      = $(LIBHOME)$(LIB_PREFIX)$(DCENAME).$(LIB_EXT)
LLIBNTOD     = $(LDLIBFLAG)$(ILIB_PREFIX)$(DCENAME)$(ILIB_SUFFIX)

LIBCDS       = $(LIBHOME)$(LIB_PREFIX)$(CDSNAME).$(LIB_EXT)
LLIBCDS      = $(LDLIBFLAG)$(ILIB_PREFIX)$(CDSNAME)$(ILIB_SUFFIX)

LIBNTLU62    = $(LIBHOME)$(LIB_PREFIX)$(LU62NAME).$(LIB_EXT)
LLIBNTLU62   = $(LDLIBFLAG)$(ILIB_PREFIX)$(LU62NAME)$(ILIB_SUFFIX)

LIBNTS       = $(LIBHOME)$(LIB_PREFIX)$(SPXNAME).$(LIB_EXT)
LLIBNTS      = $(LDLIBFLAG)$(ILIB_PREFIX)$(SPXNAME)$(ILIB_SUFFIX)

LIBNETWORK   = $(LIBHOME)$(LIB_PREFIX)$(COMMONNAME).$(LIB_EXT)
LLIBNETWORK  = $(LDLIBFLAG)$(ILIB_PREFIX)$(COMMONNAME)$(ILIB_SUFFIX)

LIBNSGR      = $(LIBHOME)$(LIB_PREFIX)$(NSGRNAME).$(LIB_EXT)
LLIBNSGR     = $(LDLIBFLAG)$(ILIB_PREFIX)$(NSGRNAME)$(ILIB_SUFFIX)

LIBSQLNET  = $(LDFLAGSFILE) $(PROTOCOLLIBD) $(NATIVELIBD) $(NATIVESYSLIBD) $(LIBNSGR) $(LIBNZJS) $(LIBNETWORK) $(LIBNL)
LLIBSQLNET = $(LDFLAGSLIST) $(PROTOCOLLIBS) $(NATIVELIBS) $(NATIVESYSLIBS) $(LLIBNCRYPT) $(LLIBNSGR) $(LLIBNZJS) $(LLIBNETWORK) $(LLIBNL)

LIBRPC       = $(LIBHOME)$(LIB_PREFIX)$(RONAME).$(LIB_EXT)
LLIBRPC      = $(LDLIBFLAG)$(ILIB_PREFIX)$(RONAME)$(ILIB_SUFFIX)

TNSLSNR	     = $(BINHOME)tnslsnr$(EXE_SUFFIX)
LSNRCTL	     = $(BINHOME)lsnrctl$(EXE_SUFFIX)

NIGTAB       = $(LIBHOME)nigtab.$(OBJ_EXT)
NIGCON       = $(LIBHOME)nigcon.$(OBJ_EXT) 
NTCONTAB     = $(LIBHOME)ntcontab.$(OBJ_EXT)
MTS_NCR	     = $(LIBHOME)ncrstab.$(OBJ_EXT)

OSNTABST     = $(NETWORKLIB)osntabst.$(OBJ_EXT)
NNFGT        = $(NETWORKLIB)nnfgt.$(OBJ_EXT)

NAETAB       = $(LIBHOME)naeet.$(OBJ_EXT) $(LIBHOME)naect.$(OBJ_EXT)
NAEDHS	     = $(LIBHOME)naedhs.$(OBJ_EXT)
NAUTAB_OBJ   = nautab.$(OBJ_EXT)
NAUTAB	     = $(LIBHOME)$(NAUTAB_OBJ)

NETLIBS      = $(LLIBSQLNET) $(LLIBRPC) $(LLIBSQLNET)
NETLIBD      = $(LIBSQLNET) $(LIBRPC)

LDFLAGSFILE=$(LIBHOME)ldflags
LDFLAGSLIST=`$(CAT) $(LDFLAGSFILE)`

LIBNTP       = $(LIBHOME)$(LIB_PREFIX)$(BEQNAME).$(LIB_EXT)
LIBNL        = $(LIBHOME)$(LIB_PREFIX)$(NLNAME).$(LIB_EXT)


# Entering /ade/b/1663622200/oracle/network/s_exports.mk


NAETAB64	= $(LIBHOME)naeet.$(OBJ_EXT) $(LIBHOME)naect.$(OBJ_EXT)
NAEDHS64	= $(LIBHOME)naedhs.$(OBJ_EXT)
NAUTAB64	= $(LIBHOME)$(NAUTAB_OBJ)

# Exiting /ade/b/1663622200/oracle/network/s_exports.mk
# Exiting /ade/b/1663622200/oracle/network/exports.mk
# Entering /ade/b/1663622200/oracle/oracore/exports.mk

COREHOME    = $(ORACLE_HOME)/oracore/
ORACOREHOME = $(COREHOME)



CORE_LIB_NAME     = core
CORE_LIB_VER      = 11
CORE_LIB          = $(CORE_LIB_NAME)$(CORE_LIB_VER)

LIBCORE_STATIC    = $(LIB_PREFIX)$(CORE_LIB).$(LIB_EXT)
LIBCORE_SHARED    = $(LIB_PREFIX)$(CORE_LIB).$(SO_EXT)
LIBCORE_SH        = $(LIB_PREFIX)$(CORE_LIB_NAME)sh$(CORE_LIB_VER).$(SO_EXT)
LIBCORE_SLH       = $(LIB_PREFIX)$(CORE_LIB).$(ILIB_EXT)

LIBCORE           = $(LIBHOME)$(LIBCORE_STATIC)
LLIBCORE          = $(LDLIBFLAG)$(CORE_LIB)
LLIBCORE_SH       = $(LDLIBFLAG)$(CORE_LIB_NAME)sh$(CORE_LIB_VER)

LIBCORE_ARC_LIB   = $(LIBCORE)
LIBCORE_SHARE_LIB = $(LIBHOME)$(LIBCORE_SHARED)

ORAZLIB              = oraz

LIBORAZLIB_STATIC    = $(LIB_PREFIX)$(ORAZLIB).$(LIB_EXT)
LIBORAZLIB_SHARED    = $(LIB_PREFIX)$(ORAZLIB).$(SO_EXT)

LIBORAZLIB           = $(LIBHOME)$(LIBORAZLIB_STATIC)
LLIBORAZLIB          = $(LDLIBFLAG)$(ORAZLIB)

LIBORAZLIB_ARC_LIB   = $(LIBORAZLIB)
LIBORAZLIB_SHARE_LIB = $(LIBHOME)$(LIBORAZLIB_SHARED)

LZOPROLIB           = lzopro

LIBLZOPRO_STATIC    = $(LIB_PREFIX)$(LZOPROLIB).$(LIB_EXT)
LIBLZOPRO_SHARED    = $(LIB_PREFIX)$(LZOPROLIB).$(SO_EXT)

LIBLZOPRO           = $(LIBHOME)$(LIBLZOPRO_STATIC)
LLIBLZOPRO          = $(LDLIBFLAG)$(LZOPROLIB)

LIBLZOPRO_ARC_LIB   = $(LIBLZOPRO)
LIBLZOPRO_SHARE_LIB = $(LIBHOME)$(LIBLZOPRO_SHARED)

ORABZ2LIB              = bz2

LIBORABZ2LIB_STATIC    = $(LIB_PREFIX)$(ORABZ2LIB).$(LIB_EXT)
LIBORABZ2LIB_SHARED    = $(LIB_PREFIX)$(ORABZ2LIB).$(SO_EXT)

LIBORABZ2LIB           = $(LIBHOME)$(LIBORABZ2LIB_STATIC)
LLIBORABZ2LIB          = $(LDLIBFLAG)$(ORABZ2LIB)

LIBORABZ2LIB_ARC_LIB   = $(LIBORABZ2LIB)
LIBORABZ2LIB_SHARE_LIB = $(LIBHOME)$(LIBORABZ2LIB_SHARED)

CORECOMPRESSLIBS = $(LLIBORAZLIB) $(LLIBLZOPRO) $(LLIBORABZ2LIB) \
                  $(PL_CORECOMPRESSLIBS)

LIB816  = /oracore/sun5/8.1.6.0.0/lib
CORE816 = $(LIB816)/$(LIBCORE_STATIC)
NLS816  = $(LIB816)/$(LIB_PREFIX)$(LIBNLSRTLNAME).$(LIB_EXT)


LIB817  = /oracore/sun5/8.1.7.0.0/lib
CORE817 = $(LIB817)/$(LIBCORE_STATIC)
NLS817  = $(LIB817)/$(LIB_PREFIX)$(LIBNLSRTLNAME).$(LIB_EXT)


S0MAIN   = $(LIBHOME)s0main.$(OBJ_EXT)
S1MAIN_C = $(COREHOME)src/corehl/lpm/sosd/main/s1main.c
SCOREPT  = $(LIBHOME)scorept.$(OBJ_EXT)
SSCOREED = $(LIBHOME)sscoreed.$(OBJ_EXT)

COREPUBLIC=$(COREHOME)include $(COREHOME)public/ $(XDKPUBLIC)

ORACOREPUBH=$(I_SYM)$(COREHOME)include $(I_SYM)$(COREHOME)public $(I_SYM)$(COREHOME)port/include $(XDKPUBH)


CORELIBD = $(LIBSNLSRTL) $(LIBNLSRTL) $(LIBCV6) $(LIBCORE) $(LIBSNLSRTL) \
           $(LIBNLSRTL) $(LIBCORE) $(LIBSNLSRTL) $(LIBNLSRTL)  $(LIBUNLSRTL) \
           $(LIBSNLSRTL) $(LIBNLSRTL)
CORELIBS = $(LLIBSNLSRTL) $(LLIBNLSRTL) $(LLIBCV6) $(LLIBCORE) $(LLIBSNLSRTL) \
           $(LLIBNLSRTL) $(LLIBCORE) $(LLIBSNLSRTL) $(LLIBNLSRTL) $(LLIBXML) \
           $(LLIBCORE) $(LLIBUNLSRTL) $(LLIBSNLSRTL) $(LLIBNLSRTL) $(LLIBCORE)\
	   $(LLIBNLSRTL)


# Entering /ade/b/1663622200/oracle/oracore/s_exports.mk


IPP_DIR=/usr/local/packages/ipp_remote/6.1.5/

IPPCORE=ippcore
LIBIPPCORE=$(LIB_PREFIX)$(IPPCORE).$(LIB_EXT)
LLIBIPPCORE=$(LDLIBFLAG)$(IPPCORE)

IPPDCEMERGED=ippdcemerged
LIBIPPDCEMERGED=$(LIB_PREFIX)$(IPPDCEMERGED).$(LIB_EXT)
LLIBIPPDCEMERGED=$(LDLIBFLAG)$(IPPDCEMERGED)

IPPDCMERGED =ippdcmerged
LIBIPPDCMERGED=$(LIB_PREFIX)$(IPPDCMERGED).$(LIB_EXT)
LLIBIPPDCMERGED=$(LDLIBFLAG)$(IPPDCMERGED)


IPPSEMERGED=ippsemerged
LIBIPPSEMERGED=$(LIB_PREFIX)$(IPPSEMERGED).$(LIB_EXT)
LLIBIPPSEMERGED=$(LDLIBFLAG)$(IPPSEMERGED)

IPPSMERGED=ippsmerged
LIBIPPSMERGED=$(LIB_PREFIX)$(IPPSMERGED).$(LIB_EXT)
LLIBIPPSMERGED=$(LDLIBFLAG)$(IPPSMERGED)

IPPSAMPLEZLIB=ipp_z
LIBIPPSAMPLEZLIB=$(LIB_PREFIX)$(IPPSAMPLEZLIB).$(LIB_EXT)
LLIBIPPSAMPLEZLIB=$(LDLIBFLAG)$(IPPSAMPLEZLIB)

IPPSAMPLEBZ2 =ipp_bz2
LIBIPPSAMPLEBZ2=$(LIB_PREFIX)$(IPPSAMPLEBZ2).$(LIB_EXT)
LLIBIPPSAMPLEBZ2=$(LDLIBFLAG)$(IPPSAMPLEBZ2)

IPPCOMPLIBS  = $(LLIBIPPDCEMERGED) $(LLIBIPPSEMERGED) \
               $(LLIBIPPDCMERGED)  $(LLIBIPPSMERGED)
IPPCORELIBS  = $(LLIBIPPCORE)
IPPSAMPLELIBS= $(LLIBIPPSAMPLEZLIB) $(LLIBIPPSAMPLEBZ2)
IPPCOMPRESSLIBS = $(IPPSAMPLELIBS) $(IPPCOMPLIBS) $(IPPCORELIBS) 


ORABZ2LIB = orabz2
 
# Exiting /ade/b/1663622200/oracle/oracore/s_exports.mk
# Exiting /ade/b/1663622200/oracle/oracore/exports.mk
# Entering /ade/b/1663622200/oracle/nlsrtl/exports.mk

NLSRTLHOME= $(ORACLE_HOME)/nlsrtl/


ORA_NLS = $(ORACLE_HOME)/ocommon/nls/admin/data/
ORA_NLS33 = $(ORACLE_HOME)/ocommon/nls/admin/data/
ORA_NLS10 = $(ORACLE_HOME)/nls/data/

NLSRTL_VERSION=11
NLSRTL_DEBUG_LIBTAG = 

LIBNLSRTLNAME = nls$(NLSRTL_VERSION)$(NLSRTL_DEBUG_LIBTAG)
LIBNLSRTL= $(LIBHOME)$(LIB_PREFIX)$(LIBNLSRTLNAME).$(LIB_EXT)
LLIBNLSRTL= $(LDLIBFLAG)$(LIBNLSRTLNAME)$(LIB_SUFFIX)

LIBUNLSRTLNAME = unls$(NLSRTL_VERSION)$(NLSRTL_DEBUG_LIBTAG)
LIBUNLSRTL= $(LIBHOME)$(LIB_PREFIX)$(LIBUNLSRTLNAME).$(LIB_EXT)
LLIBUNLSRTL= $(LDLIBFLAG)$(LIBUNLSRTLNAME)$(LIB_SUFFIX)

LIBSNLSRTLNAME = snls$(NLSRTL_VERSION)$(NLSRTL_DEBUG_LIBTAG)
LIBSNLSRTL= $(LIBHOME)$(LIB_PREFIX)$(LIBSNLSRTLNAME).$(LIB_EXT)
LLIBSNLSRTL= $(LDLIBFLAG)$(LIBSNLSRTLNAME)$(LIB_SUFFIX)

NLSRTLPUBH = $(I_SYM)$(NLSRTLHOME)include

GSSHOME = $(ORACLE_HOME)/nlsrtl3/java
GSSCLASSES11 = $(ORACLE_HOME)/jlib/orai18n.jar
GSSCLASSES12 = $(ORACLE_HOME)/jlib/orai18n.jar
GSSCHARSET11 = $(ORACLE_HOME)/jlib/orai18n.jar
GSSCHARSET12 = $(ORACLE_HOME)/jlib/orai18n.jar

GDKHOME = $(ORACLE_HOME)/nlsrtl3/java
GDKCLASSES = $(ORACLE_HOME)/jlib/orai18n.jar$(PATHSEP)$(ORACLE_HOME)/jlib/orai18n-lcsd.jar
NLSRTL_JARS = \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-mapping.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-utility.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-collation.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-translation.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-net.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-servlet.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-tools.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-lcsd.jar

NLSRTL_JARS_FOR_GENERAL = \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-mapping.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-utility.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-collation.jar

NLSRTL_JARS_FOR_DBJAVA_JAVAVM = \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-mapping.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-utility.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-collation.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-net.jar

NLSRTL_JARS_FOR_DBJAVA_CLIENT = \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n.jar \
  $(ORACLE_HOME)/nlsrtl3/jlib/orai18n-mapping.jar

NLSRTL_SHIPHOME_JARS_FOR_DBJAVA_CLIENT = \
  $(ORACLE_HOME)/jlib/orai18n.jar \
  $(ORACLE_HOME)/jlib/orai18n-mapping.jar

# Entering /ade/b/1663622200/oracle/nlsrtl/s_exports.mk

LIBNLSRTLSHNAME = nlssh$(NLSRTL_VERSION)$(NLSRTL_DEBUG_LIBTAG)
LIBUNLSRTLSHNAME = unlssh$(NLSRTL_VERSION)$(NLSRTL_DEBUG_LIBTAG)
LIBSNLSRTLSHNAME = snlssh$(NLSRTL_VERSION)$(NLSRTL_DEBUG_LIBTAG)

LLIBNLSSH=-lnlssh$(NLSRTL_VERSION)
LLIBSNLSSH=-lsnlssh$(NLSRTL_VERSION)
LLIBUNLSSH=-lunlssh$(NLSRTL_VERSION)

# Exiting /ade/b/1663622200/oracle/nlsrtl/s_exports.mk
# Exiting /ade/b/1663622200/oracle/nlsrtl/exports.mk
# Entering /ade/b/1663622200/oracle/rdbms/exports.mk


RDBMS_VERSION=11
RDBMS_MINOR_VERSION=1

LIBCLNTSTNAME=clntst$(RDBMS_VERSION)
LIBCLNTST=$(LIBHOME)$(LIB_PREFIX)$(LIBCLNTSTNAME).$(LIB_EXT)
LLIBCLNTST=$(LDLIBFLAG)$(LIBCLNTSTNAME)

LIBSERVERNAME=server$(RDBMS_VERSION)
LIBSERVER=$(LIBHOME)$(LIB_PREFIX)$(LIBSERVERNAME).$(LIB_EXT)
LLIBSERVER=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBSERVERNAME)$(LIB_SUFFIX)

LIBCLIENTNAME=client$(RDBMS_VERSION)
LIBCLIENT=$(LIBHOME)$(LIB_PREFIX)$(LIBCLIENTNAME).$(DEPLIB_EXT)
LLIBCLIENT=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBCLIENTNAME)$(ILIB_SUFFIX)

LIBGENERICNAME=generic$(RDBMS_VERSION)
LIBGENERIC=$(LIBHOME)$(LIB_PREFIX)$(LIBGENERICNAME).$(DEPLIB_EXT)
LLIBGENERIC=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBGENERICNAME)$(ILIB_SUFFIX)

LIBSKGXPNAME=skgxp$(RDBMS_VERSION)
LIBSKGXP=$(LIBHOME)$(LIB_PREFIX)$(LIBSKGXPNAME).$(SKGXP_EXT)
LLIBSKGXP=$(LDLIBFLAG)$(LIBSKGXPNAME)

LIBSKGTRNAME=skgtr$(RDBMS_VERSION)
LIBSKGTR_MPMT=$(LIBHOME)$(LIB_PREFIX)$(LIBSKGTRNAME).$(SKGTR_EXT)
LIBSKGTR_=
LIBSKGTR=$(LIBSKGTR_$(MPMT_SERVER))
LLIBSKGTR_MPMT=$(LDLIBFLAG)$(LIBSKGTRNAME)
LLIBSKGTR_=
LLIBSKGTR=$(LLIBSKGTR_$(MPMT_SERVER))

LIBASMCLNTNAME=asmclnt$(RDBMS_VERSION)
LIBASMCLNT=$(LIBHOME)$(LIB_PREFIX)$(LIBASMCLNTNAME).$(DEPLIB_EXT)
LLIBASMCLNT=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBASMCLNTNAME)$(ILIB_SUFFIX)
LIBASMCLNT_DEPS=$(LLIBCLNTSH) $(LLIBHASGEN) $(LLIBSKGXN) $(LLIBCOMMON) $(LLIBOCR) $(LLIBGENERIC) $(LLIBSAGE) $(LLIBSKGXP) $(LLIBXML)

LIBASMCLNTSHNAME=asmclntsh$(RDBMS_VERSION)
LIBASMCLNTSH=$(LIBHOME)$(LIB_PREFIX)$(LIBASMCLNTSHNAME).$(DEPSO_EXT)
LLIBASMCLNTSH=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBASMCLNTSHNAME)$(ILIB_SUFFIX)
LIBASMCLNTSH_DEPS=$(LLIBCLNTSH) $(LLIBHASGEN) $(LLIBSKGXN) $(LLIBCOMMON) $(LLIBOCR) $(LLIBGENERIC) $(LLIBSAGE) $(LLIBSKGXP) $(LLIBXML)

ENCRYPTLIBS = $(PL_ENCRYPTLIBS)

LIBSKGXNNAME=skgxn$(RDBMS_VERSION)
LIBSKGXN=$(LIBHOME)$(LIB_PREFIX)$(LIBSKGXNNAME).$(SKGXN_EXT)
LLIBSKGXN=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBSKGXNNAME)$(LIB_SUFFIX)
LIBSKGXNI=$(LIBHOME)$(LIB_PREFIX)$(LIBSKGXNNAME).$(SKGXN_EXT)

LIBOCCINAME=occi
LIBOCCI=$(LIBHOME)$(LIB_PREFIX)$(LIBOCCINAME)$(RDBMS_VERSION).$(LIB_EXT)
LLIBOCCI=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBOCCINAME)$(RDBMS_VERSION)$(ILIB_SUFFIX)
LLIBOCCISTATIC=$(LDLIBFLAG)$(LIBOCCINAME)$(RDBMS_VERSION)

LIBCDFNAME=cdf
LIBCDF=$(LIBHOME)$(LIB_PREFIX)$(LIBCDFNAME)$(RDBMS_VERSION).$(LIB_EXT)
LLIBCDF=$(LDLIBFLAG)$(LIBCDFNAME)$(RDBMS_VERSION)

LIBWSECNAME=wsec
LIBWSEC=$(LIBHOME)$(LIB_PREFIX)wsec$(RDBMS_VERSION).$(LIB_EXT)
LLIBWSEC=$(LDLIBFLAG)$(LIB_PREFIX)$(LIBWSECNAME)$(RDBMS_VERSION)$(ILIB_SUFFIX)

LIBSKGXP_CLT=
LLIBSKGXP_CLT=

LIBCOMMONNAME=common$(RDBMS_VERSION)
LIBCOMMON=$(LIBHOME)$(LIB_PREFIX)$(LIBCOMMONNAME).$(DEPLIB_EXT)
LLIBCOMMON=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBCOMMONNAME)$(ILIB_SUFFIX)

LIBEVANAME=eva$(RDBMS_VERSION)
LIBEVA=$(LIBHOME)$(LIB_PREFIX)$(LIBEVANAME).$(LIB_EXT)
LLIBEVA=$(LDLIBFLAG)$(LIBEVANAME)

LIBVSNNAME=vsn$(RDBMS_VERSION)
LIBVSN=$(LIBHOME)$(LIB_PREFIX)$(LIBVSNNAME).$(DEPLIB_EXT)
LLIBVSN=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBVSNNAME)$(ILIB_SUFFIX)

LIBAGENTNAME=agent$(RDBMS_VERSION)
LIBAGENT=$(LIBHOME)$(LIB_PREFIX)$(LIBAGENTNAME).$(LIB_EXT)
LLIBAGENT=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBAGENTNAME)$(LIB_SUFFIX)

LIBHGOSHNAME=hgosh$(RDBMS_VERSION)
LIBHGOSH=$(LIBHOME)$(LIB_PREFIX)$(LIBHGOSHNAME).$(LIB_EXT)
LLIBHGOSH=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGOSHNAME)$(LIB_SUFFIX)

LIBHGMSQLNAME=hgmsql$(RDBMS_VERSION)
LIBHGMSQL=$(LIBHOME)$(LIB_PREFIX)$(LIBHGMSQLNAME).$(LIB_EXT)
LLIBHGMSQL=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGMSQLNAME)$(LIB_SUFFIX)

LIBHGSYBSNAME=hgsybs$(RDBMS_VERSION)
LIBHGSYBS=$(LIBHOME)$(LIB_PREFIX)$(LIBHGSYBSNAME).$(LIB_EXT)
LLIBHGSYBS=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGSYBSNAME)$(LIB_SUFFIX)

LIBHGIFMXNAME=hgifmx$(RDBMS_VERSION)
LIBHGIFMX=$(LIBHOME)$(LIB_PREFIX)$(LIBHGIFMXNAME).$(LIB_EXT)
LLIBHGIFMX=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGIFMXNAME)$(LIB_SUFFIX)

LIBHGTERANAME=hgtera$(RDBMS_VERSION)
LIBHGTERA=$(LIBHOME)$(LIB_PREFIX)$(LIBHGTERANAME).$(LIB_EXT)
LLIBHGTERA=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGTERANAME)$(LIB_SUFFIX)

LIBHGDB2NAME=hgdb2$(RDBMS_VERSION)
LIBHGDB2=$(LIBHOME)$(LIB_PREFIX)$(LIBHGDB2NAME).$(LIB_EXT)
LLIBHGDB2=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGDB2NAME)$(LIB_SUFFIX)

LIBHGGCONNAME=hggcon$(RDBMS_VERSION)
LIBHGGCON=$(LIBHOME)$(LIB_PREFIX)$(LIBHGGCONNAME).$(LIB_EXT)
LLIBHGGCON=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGGCONNAME)$(LIB_SUFFIX)

LIBHGOTRACENAME=hgotrace$(RDBMS_VERSION)
LIBHGOTRACE=$(LIBHOME)$(LIB_PREFIX)$(LIBHGOTRACENAME).$(SO_EXT)
LLIBHGOTRACE=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBHGOTRACENAME)$(LIB_SUFFIX)

LIBDBTOOLSNAME=dbtools$(RDBMS_VERSION)
LIBDBTOOLS=$(RDBMSLIB)$(LIB_PREFIX)$(LIBDBTOOLSNAME).$(LIB_EXT)
LLIBDBTOOLS=$(LDLIBFLAG)$(LIBDBTOOLSNAME)

LIBNNETNAME=nnet$(RDBMS_VERSION)
LIBNNET=$(RDBMSLIB)$(LIB_PREFIX)$(LIBNNETNAME).$(LIB_EXT)
LLIBNNET=$(LDLIBFLAG)$(LIBNNETNAME)

LIBNNETDNAME=nnetd$(RDBMS_VERSION)
LIBNNETD=$(RDBMSLIB)$(LIB_PREFIX)$(LIBNNETDNAME).$(LIB_EXT)
LLIBNNETD=$(LDLIBFLAG)$(LIBNNETDNAME)

LIBNNET_CLT=$(LIBNNETD)
LLIBNNET_CLT=$(LLIBNNETD)

DLMHOME=$(ORACLE_HOME)/odlm/

LIBMMNAME=mm
LIBMM=$(LIBHOME)$(LIB_PREFIX)$(LIBMMNAME).$(LIB_EXT)
LLIBMM=$(LDLIBFLAG)$(LIBMMNAME)


LIBRDBMS_CLT=$(LIBCLIENT) $(LIBNNET_CLT) $(LIBSKGXP_CLT) $(LIBVSN) \
	$(LIBCOMMON) $(LIBGENERIC)
LLIBRDBMS_CLT=$(LLIBCLIENT) $(LLIBNNET_CLT) $(LLIBSKGXP_CLT) $(LLIBVSN) \
	$(LLIBCOMMON) $(LLIBGENERIC)

LIBRDBMS_SERVER=$(LIBCLIENT) $(LIBSKGXP_CLT) $(LIBVSN) \
	$(LIBCOMMON) $(LIBGENERIC)
LLIBRDBMS_SERVER=$(LLIBCLIENT) $(LLIBSKGXP_CLT) $(LLIBVSN) \
	$(LLIBCOMMON) $(LLIBGENERIC)

LIBCLNTSHNAME=clntsh
LIBCLNTSH=$(LIBHOME)$(LIB_PREFIX)$(LIBCLNTSHNAME).$(SO_EXT)
LLIBCLNTSH=$(LDLIBFLAG)$(LIBCLNTSHNAME)
LIBCLNTSH_NPT=
LLIBCLNTSH_NPT=

LIBAGTSHNAME=agtsh
LIBAGTSH=$(LIBHOME)$(LIB_PREFIX)$(LIBAGTSHNAME).$(SO_EXT)
LLIBAGTSH=$(LDLIBFLAG)$(LIBAGTSHNAME)

LIBKNLOPTNAME=knlopt
LIBKNLOPT=$(RDBMSLIB)$(LIB_PREFIX)$(LIBKNLOPTNAME).$(LIB_EXT)
LLIBKNLOPT=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBKNLOPTNAME)$(LIB_SUFFIX)

LIBAVSTUBNAME=avstub$(RDBMS_VERSION)
LIBAVSTUB=$(LIBHOME)$(LIB_PREFIX)$(LIBAVSTUBNAME).$(LIB_EXT)
LLIBAVSTUB=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBAVSTUBNAME)$(LIB_SUFFIX)

LIBAVSERVERNAME=avserver$(RDBMS_VERSION)
LIBAVSERVER=$(LIBHOME)$(LIB_PREFIX)$(LIBAVSERVERNAME).$(LIB_EXT)
LLIBAVSERVER=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBAVSERVERNAME)$(LIB_SUFFIX)

LIBAVCLIENTNAME=avclient$(RDBMS_VERSION)
LIBAVCLIENT=$(LIBHOME)$(LIB_PREFIX)$(LIBAVCLIENTNAME).$(LIB_EXT)
LLIBAVCLIENT=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBAVCLIENTNAME)$(LIB_SUFFIX)

AVLIBS = `if [ -f $(LIBAVSERVER) ] ; then echo "$(LLIBAVSERVER)" ; else echo "$(LLIBAVSTUB)"; fi` `if [ -f $(LIBAVCLIENT) ] ; then echo "$(LLIBAVCLIENT)" ; fi`

LIBORASDKBASENAME=orasdkbase
LIBORASDKBASE=$(LIBHOME)$(LIB_PREFIX)$(LIBORASDKBASENAME).$(SO_EXT)
LLIBORASDKBASE=$(LDLIBFLAG)$(LIBORASDKBASENAME)

LIBORASDKSHNAME=orasdk
LIBORASDKSH=$(LIBHOME)$(LIB_PREFIX)$(LIBORASDKSHNAME).$(SO_EXT)
LLIBORASDKSH=$(LDLIBFLAG)$(LIBORASDKSHNAME)

CONFIG = $(RDBMSLIB)config.$(OBJ_EXT)


LLIBORDSDO=$(LDLIBFLAG)$(LIBORDSDONAME)$(LIB_SUFFIX)
SDOLIBS = `if ${AR} tv $(LIBKNLOPT) | $(GREP) "kxmnsd.$(OBJ_EXT)" > /dev/null 2>&1 ; then echo " " ; else echo "${LLIBORDSDO}"; fi`

RDBMSHOME=$(ORACLE_HOME)/rdbms/
RDBMSLIB=$(RDBMSHOME)$(LIBDIR)/
RDBMSADMIN=$(RDBMSHOME)admin/

ORAMAPLIB=$(RDBMSLIB)

LIBNIDNAME=nid
LIBNID=$(RDBMSLIB)$(LIB_PREFIX)$(LIBNIDNAME).$(LIB_EXT)
LLIBNID=$(LDLIBFLAG)$(LIBNIDNAME)

THREAD_ORALIBS_MPMT=-lpthread
THREAD_ORALIBS_=
THREAD_ORALIBS=$(THREAD_ORALIBS_$(MPMT_SERVER))


ORACLE_KERNEL_LIBS=$(LLIBSKGTR) $(LLIBPERFSRV) $(NAETTOBJS) $(CONFIG)\
	$(SPOBJS) $(LLIBSERVER) $(LLIBODM) $(LLIBSAGE) \
	$(LLIBNNET) $(LLIBSKGXP) $(CORELIBS) $(LLIBRDBMS_SERVER) \
	$(LLIBKNLOPT) $(OLAPLINKOPTS) \
	$(LLIBSLAX) $(LLIBPLSQL) $(LLIBSERVER) $(LLIBRDBMS_SERVER) $(AVLIBS) \
	$(LLIBKNLOPT) $(LLIBSLAX) $(LLIBPLSQL) $(LLIBJAVAVMORJOX) \
	$(LLIBOCIJDBCST) $(LLIBWWG) $(NTZEOBJ) $(NETLIBS) $(NZLIBS) $(LLIBMM) $(CORELIBS) $(LLIBZTKG)\
	$(NETLIBS) $(NZLIBS) $(LIBPLS_CLT) $(LLIBEPC) $(CORELIBS) $(SDOLIBS) $(CARTLIBS) \
	$(CLSRLIBS_SERVER) $(CSSCLNTLIBS_SERVER) \
        $(CORECOMPRESSLIBS) $(ENCRYPTLIBS)  \
	$(CORELIBS) $(LLIBSNLSRTL) $(LLIBUNLSRTL) $(LLIBXSD) $(CORELIBS) \
	$(LLIBASMCLNT) $(LLIBCOMMON) $(LLIBCORE) $(PL_ORALIBS) $(THREAD_ORALIBS)
LIBCLIENTSHNAME=clientsh$(RDBMS_VERSION)
LLIBCLIENTSH=$(LDLIBFLAG)$(LIBCLIENTSHNAME)$(LIB_SUFFIX)
LIBGENERICSHNAME=genericsh$(RDBMS_VERSION)
LLIBGENERICSH=$(LDLIBFLAG)$(LIBGENERICSHNAME)$(LIB_SUFFIX)
LIBCOMMONSHNAME=commonsh$(RDBMS_VERSION)
LLIBCOMMONSH=$(LDLIBFLAG)$(LIBCOMMONSHNAME)$(LIB_SUFFIX)
LIBMMSHNAME=mmsh
LLIBMMSH=$(LDLIBFLAG)$(LIBMMSHNAME)$(LIB_SUFFIX)
LIBVSNSHNAME=vsnsh$(RDBMS_VERSION)
LLIBVSNSH=$(LDLIBFLAG)$(LIBVSNSHNAME)$(LIB_SUFFIX)
LIBNNETSHNAME=nnetsh$(RDBMS_VERSION)
LLIBNNETSH=$(LDLIBFLAG)$(LIBNNETSHNAME)$(LIB_SUFFIX)

LIBORIONNAME=orion$(RDBMS_VERSION)
LIBORION=$(LIBHOME)$(LIB_PREFIX)$(LIBORIONNAME).$(LIB_EXT)
LLIBORION=$(LDLIBFLAG)$(LIBORIONNAME)

LIBDSGANAME=dsga$(RDBMS_VERSION)
LIBDSGA=$(RDBMSLIB)$(LIB_PREFIX)$(LIBDSGANAME).$(LIB_EXT)
LLIBDSGA=$(LDLIBFLAG)$(LIBDSGANAME)
LOC_LIBDSGA=$(RDBMSLIB)$(LIB_PREFIX)$(LIBDSGANAME).$(LIB_EXT)

LIBDBGUISSNAME=dbguiss
LOC_LIBDBGUISS=$(RDBMSLIB)$(LIB_PREFIX)$(LIBDBGUISSNAME).$(LIB_EXT)
LIBDBGUISS=$(RDBMSLIB)$(LIB_PREFIX)$(LIBDBGUISSNAME).$(SO_EXT)
LLIBDBGUISS=$(LDLIBFLAG)$(LIBDBGUISSNAME)

ASMCLNT_LIBS=$(LLIBASMCLNT) $(LLIBCOMMON) $(LLIBSAGE) $(LLIBSKGXP) \
             $(LLIBGENERIC)
ASMCLNTSH_LIBS=$(LLIBASMCLNTSH) $(LLIBSAGE) $(LLIBSKGXP)
ASMCLNT_OCR_LIBS=$(ASMCLNT_LIBS)
ASMCLNT_CSS_LIBS=$(ASMCLNT_LIBS)


LINK_JOX_STATICALLY=yes

# Entering /ade/b/1663622200/oracle/rdbms/export_banner.mk

# Exiting /ade/b/1663622200/oracle/rdbms/export_banner.mk
# Entering /ade/b/1663622200/oracle/rdbms/s_exports.mk
 
LIBPERFSRVNAME=perfsrv$(RDBMS_VERSION)
LIBPERFSRV=$(LIBHOME)$(LIB_PREFIX)$(LIBPERFSRVNAME).$(LIB_EXT)
LLIBPERFSRV=$(LDLIBFLAG)$(LIBPERFSRVNAME)$(LIB_SUFFIX)


SKGXP_EXT=$(SO_EXT)
 
 


SKGXN_EXT=$(LIB_EXT)

SKGXN_VERSION=2
LIBSKGXNNAME=skgxn$(SKGXN_VERSION)
LIBSKGXN=$(ORACLUSTERDIR)$(LIB_PREFIX)$(LIBSKGXNNAME).$(SKGXN_EXT)


LIBCLNTSH=$(LIBHOME)$(LIB_PREFIX)$(LIBCLNTSHNAME).$(SO_EXT)
LLIBCLNTSH=$(LDLIBFLAG)$(LIBCLNTSHNAME) -brtl
LIBCLNTSH64=$(ORACLE_HOME)/lib64/libclntsh.$(LIB_EXT)

LIBAGTSH=$(LIBHOME)$(LIB_PREFIX)$(LIBAGTSHNAME).$(LIB_EXT)

SDOLIBS = `if ${AR} tv $(LIBKNLOPT) | $(GREP) "kxmnsd.o" > /dev/null 2>&1 ; then echo " " ; else echo "${LLIBORDSDO}"; fi`

LLIBOCCI=$(LDLIBFLAG)$(LIBOCCINAME)
LIBOCCI=$(LIBHOME)$(LIB_PREFIX)$(LIBOCCINAME).$(LIB_EXT)

AIO_NWAIT_TIMEOUT_EXP= -bI:/usr/lib/aio.exp


DSGALIBLIST=$(RDBMSLIB)dsgaliblist

LIBASMCLNT_STATIC=$(LIBHOME)$(LIB_PREFIX)$(LIBASMCLNTNAME).$(LIB_EXT)
LIBSAGE_STATIC=$(LIBHOME)$(LIB_PREFIX)$(LIBSAGENAME).$(LIB_EXT)
ASMCLNT_OCR_LIBS=$(LIBASMCLNT_STATIC) \
                 $(LLIBCOMMON) $(LIBSAGE_STATIC) $(LLIBGENERIC) 
ASMCLNT_CSS_LIBS=$(LIBASMCLNT_STATIC) \
                 $(LLIBCOMMON) $(LIBSAGE_STATIC) $(LLIBGENERIC) 

LIBASMCLNTSH_STATIC=$(LIBHOME)$(LIB_PREFIX)$(LIBASMCLNTSHNAME).$(LIB_EXT)
ASMCLNTSH_LIBS=$(LIBASMCLNTSH_STATIC) $(LIBSAGE_STATIC) 

# Exiting /ade/b/1663622200/oracle/rdbms/s_exports.mk
# Exiting /ade/b/1663622200/oracle/rdbms/exports.mk
# Entering /ade/b/1663622200/oracle/plsql/exports.mk

PLSQL_VERSION=11

WRAP=$(BINHOME)wrap

LIBPLSNAME=pls
LIBPLSN=$(LIBHOME)$(LIB_PREFIX)$(LIBPLSNAME)$(PLSQL_VERSION).$(DEPLIB_EXT)
LLIBPLS=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBPLSNAME)$(PLSQL_VERSION)$(ILIB_SUFFIX) 
LIBPLSNSHR=$(LIBHOME)/$(LIB_PREFIX)$(LIBPLSNAME).$(SO_EXT)
ILIBPLSN=$(LIBHOME)/$(LIB_PREFIX)$(LIBPLSNAME).$(ILIB_EXT)
LIBPLPNAME=plp
LIBPLPN=$(LIBHOME)$(LIB_PREFIX)$(LIBPLPNAME)$(PLSQL_VERSION).$(DEPLIB_EXT)
LLIBPLP=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBPLPNAME)$(PLSQL_VERSION)$(ILIB_SUFFIX)
LIBPLPNSHR=$(LIBHOME)/$(LIB_PREFIX)$(LIBPLPNAME).$(SO_EXT)
ILIBPLPN=$(LIBHOME)/$(LIB_PREFIX)$(LIBPLPNAME).$(ILIB_EXT)
LIBPLCNAME=plc
LIBPLCN=$(LIBHOME)$(LIB_PREFIX)$(LIBPLCNAME)$(PLSQL_VERSION).$(DEPLIB_EXT)
LLIBPLC=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBPLCNAME)$(PLSQL_VERSION)$(ILIB_SUFFIX)
LIBPLCSHR=$(LIBHOME)/$(LIB_PREFIX)$(LIBPLCNAME).$(SO_EXT)
ILIBPLCN=$(LIBHOME)/$(LIB_PREFIX)$(LIBPLCNAME).$(ILIB_EXT)

LIBEXTP=$(LIBHOME)$(LIB_PREFIX)$(LIBPLSNAME)$(PLSQL_VERSION).$(DEPLIB_EXT)
LLIBEXTP=$(LDLIBFLAG)$(LIBPLSNAME)$(PLSQL_VERSION)

LIBPLSF=$(LIBHOME)$(LIB_PREFIX)$(LIBPLSNAME)$(PLSQL_VERSION).$(LIB_EXT) 
LLIBPLSF=$(LDLIBFLAG)$(LIBPLSNAME)$(PLSQL_VERSION) $(LDLIBFLAG)$(LIBPLPNAME)$(PLSQL_VERSION)

LIBPLSB=$(LIBHOME)$(LIBPLSNAME)$(PLSQL_VERSION)
LLIBPLSB=$(LDLIBFLAG)$(LIBPLSNAME)$(PLSQL_VERSION)

PLSQLLIBS=$(LIBPLSN) $(LIBPLPN)
LPLSQLLIBS=$(LLIBPLS)


LLIBPLSQL= $(LPLSQLLIBS) $(LLIBPLP)

LIBPSANAME=psa
LIBICD=$(LIBHOME)$(LIB_PREFIX)$(LIBPLPNAME)$(PLSQL_VERSION).$(LIB_EXT)
LLIBICD=$(LDLIBFLAG)$(LIBPLPNAME)$(PLSQL_VERSION)
LIBPSD=$(LIBHOME)$(LIB_PREFIX)$(LIBPLCNAME)$(PLSQL_VERSION).$(LIB_EXT)
LLIBPSD=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBPLCNAME)$(PLSQL_VERSION)$(LIB_SUFFIX)
LIBPSA=$(LIBHOME)$(LIB_PREFIX)$(LIBPSANAME)$(PLSQL_VERSION).$(LIB_EXT)
LLIBPSA=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBPSANAME)$(PLSQL_VERSION)$(LIB_SUFFIX)

PLSQLHOME=$(ORACLE_HOME)/plsql/

PLSSHNAME=plssh$(PLSQL_VERSION)
LLIBPLSSH=$(LDLIBFLAG)$(PLSSHNAME)$(LIB_SUFFIX)
PLPSHNAME=plpsh$(PLSQL_VERSION)
LLIBPLPSH=$(LDLIBFLAG)$(PLPSHNAME)$(LIB_SUFFIX)
# Entering /ade/b/1663622200/oracle/plsql/s_exports.mk

PLSQL_NCOMP_EXP=-bE:$(RDBMSLIB)plsqlncomp.exp
PLS_EXP=-bE:$(PLSQLHOME)admin/libpls11.exp


LLIBPLS+=-lrt
 
# Exiting /ade/b/1663622200/oracle/plsql/s_exports.mk
# Exiting /ade/b/1663622200/oracle/plsql/exports.mk
# Entering /ade/b/1663622200/oracle/slax/exports.mk

TOP = $(ORACLE_HOME)/slax

SLAX_VERSION=11
LIBSLAXNAME=slax$(SLAX_VERSION)
LLIBSLAX=$(LDLIBFLAG)$(LIBSLAXNAME)$(LIB_SUFFIX)
LIBSLAX=$(LIBHOME)$(LIB_PREFIX)$(LIBSLAXNAME).$(LIB_EXT)

SLAX_PRD=slax
SLAXHOME=$(ORACLE_HOME)/slax/
SLAXADMIN=$(SLAXHOME)admin/
SLAXLIB=$(SLAXHOME)$(LIBDIR)/
 
SLAXPUBH=$(I_SYM)$(SLAXHOME)include

# Entering /ade/b/1663622200/oracle/slax/s_exports.mk

# Exiting /ade/b/1663622200/oracle/slax/s_exports.mk
# Exiting /ade/b/1663622200/oracle/slax/exports.mk
# Entering /ade/b/1663622200/oracle/xdk/exports.mk

XDKHOME    = $(ORACLE_HOME)/xdk/

XDK_LIB_VER    = 11



XML_LIB_NAME     = xml
XML_LIB_VER      = $(XDK_LIB_VER)
XML_LIB          = $(XML_LIB_NAME)$(XML_LIB_VER)

LIBXML_STATIC    = $(LIB_PREFIX)$(XML_LIB).$(LIB_EXT)
LIBXML_SHARED    = $(LIB_PREFIX)$(XML_LIB).$(SO_EXT)
LIBXML_SLH       = $(LIB_PREFIX)$(XML_LIB).$(ILIB_EXT)

LIBXML           = $(LIBHOME)$(LIBXML_STATIC)
LLIBXML          = $(LDLIBFLAG)$(XML_LIB)

LIBXML_ARC_LIB   = $(LIBXML)
LIBXML_SHARE_LIB = $(LIBHOME)$(LIBXML_SHARED)

XDKPUBLIC=$(XDKHOME)include $(XDKHOME)public

XDKPUBH=$(I_SYM)$(XDKHOME)include $(I_SYM)$(XDKHOME)public



XMLORGJAR = $(XDKSRC)java/lib/xmlorg.jar
XMLORG1JAR = $(XDKSRC)java/lib/xmlorg1.jar
JAXP_SERVICESJAR = $(XDKSRC)java/lib/jaxp_services.jar

XMLORG2JAR = $(XDKSRC)java/lib/xmlorg2.jar

JAXB2JAR = $(XDKSRC)java/lib/jaxb-api.jar


XML = xml
XMLJAR = $(LIBHOME)$(XML).$(JAR_EXT)

XMLPARSERV2 = xmlparserv2
XMLPARSERV2A = xmlparserv2_sans_jaxp_services
XMLPARSERV2B = xmlparserv2_jaxp_services

XMLPARSERV2JAR = $(LIBHOME)$(XMLPARSERV2).$(JAR_EXT)
XMLPARSERV2AJAR = $(LIBHOME)$(XMLPARSERV2A).$(JAR_EXT)
XMLPARSERV2BJAR = $(LIBHOME)$(XMLPARSERV2B).$(JAR_EXT)

XMLMESG = xmlmesg
XMLMESGJAR = $(LIBHOME)$(XMLMESG).$(JAR_EXT)

XMLCOMP = xmlcomp
XMLCOMPJAR = $(LIBHOME)$(XMLCOMP).$(JAR_EXT)

XMLCOMP2 = xmlcomp2
XMLCOMP2JAR = $(LIBHOME)$(XMLCOMP2).$(JAR_EXT)

XMLDEMO = xmldemo

CLASSGEN = classgen
CLASSGENJAR = $(LIBHOME)$(CLASSGEN).$(JAR_EXT)

XSCHEMA = xschema
XSCHEMAJAR  = $(LIBHOME)$(XSCHEMA).$(JAR_EXT)

XSQL = oraclexsql
XSQLJAR = $(LIBHOME)$(XSQL).$(JAR_EXT)

XSQLSERIAL = xsqlserializers
XSQLSERIALJAR = $(LIBHOME)$(XSQLSERIAL).$(JAR_EXT)

XSU = xsu12
XSUJAR = $(LIBHOME)$(XSU).$(JAR_EXT)

TRANSX = transx
TRANSXJAR  = $(LIBHOME)$(TRANSX).$(ZIP_EXT)

JAXBJAR = $(XDKSRC)java/lib/jaxb-api.jar

XQUERY = xquery
XQUERYJAR  = $(LIBHOME)$(XQUERY).$(JAR_EXT)

XQJAPI = xqjapi
XQJAPIJAR  = $(LIBHOME)$(XQJAPI).$(JAR_EXT)

XQJORI = xqjori
XQJORIJAR  = $(LIBHOME)$(XQJORI).$(JAR_EXT)

OJCR = ojcr
OJCRJAR  = $(LIBHOME)$(OJCR).$(JAR_EXT)


# Entering /ade/b/1663622200/oracle/xdk/s_exports.mk
 
# Exiting /ade/b/1663622200/oracle/xdk/s_exports.mk

# Exiting /ade/b/1663622200/oracle/xdk/exports.mk
# Entering /ade/b/1663622200/oracle/javavm/exports.mk
JAVAVMFORRDBMSBASENAME = javavm$(RDBMS_VERSION)
LIBJAVAVMFORRDBMSBASENAME = $(LIB_PREFIX)$(JAVAVMFORRDBMSBASENAME)
LIBJAVAVM=$(LIBHOME)$(LIBJAVAVMFORRDBMSBASENAME).$(LIB_EXT)
LLIBJAVAVM=$(LDLIBFLAG)$(JAVAVMFORRDBMSBASENAME)

# Entering /ade/b/1663622200/oracle/javavm/javavm_common.mk

# Exiting /ade/b/1663622200/oracle/javavm/javavm_common.mk
# Entering /ade/b/1663622200/oracle/javavm/s_exports.mk

# Exiting /ade/b/1663622200/oracle/javavm/s_exports.mk
# Exiting /ade/b/1663622200/oracle/javavm/exports.mk

# Entering /ade/b/1663622200/oracle/dbjava/exports.mk

JDBCHOME=$(ORACLE_HOME)/dbjava/

JDBC_VERSION = 11
JDBC_MAJOR_VERSION = 11
JDBC_MINOR_VERSION = 2
JDBC_VERSION_STRING = \"11.2.0.3.0\"

JDBC_LABEL_JAR_PATH=$(ORACLE_HOME)/dbjava/lib/
JDBC_SHIPHOME_JAR_PATH=$(ORACLE_HOME)/jdbc/lib/

JDBC_PREVIOUS_JDK_OPT_JAR_NAME=
JDBC_PREVIOUS_JDK_DEBUG_JAR_NAME=
JDBC_PREVIOUS_JDK_DMS_JAR_NAME=
JDBC_PREVIOUS_JDK_DMS_DEBUG_JAR_NAME=

JDBC_CURRENT_JDK_OPT_JAR_NAME=ojdbc5.jar
JDBC_CURRENT_JDK_DEBUG_JAR_NAME=ojdbc5_g.jar
JDBC_CURRENT_JDK_DMS_JAR_NAME=ojdbc5dms.jar
JDBC_CURRENT_JDK_DMS_DEBUG_JAR_NAME=ojdbc5dms_g.jar

JDBC_NEXT_JDK_OPT_JAR_NAME=ojdbc6.jar
JDBC_NEXT_JDK_DEBUG_JAR_NAME=ojdbc6_g.jar
JDBC_NEXT_JDK_DMS_JAR_NAME=ojdbc6dms.jar
JDBC_NEXT_JDK_DMS_DEBUG_JAR_NAME=ojdbc6dms_g.jar


JDBC_PREVIOUS_JDK_OPT_JAR=
JDBC_PREVIOUS_JDK_SHIPHOME_OPT_JAR=
JDBC_PREVIOUS_JDK_DEBUG_JAR=
JDBC_PREVIOUS_JDK_DMS_JAR=
JDBC_PREVIOUS_JDK_DMS_DEBUG_JAR=

JDBC_CURRENT_JDK_OPT_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_CURRENT_JDK_OPT_JAR_NAME)
JDBC_CURRENT_JDK_SHIPHOME_OPT_JAR=$(JDBC_SHIPHOME_JAR_PATH)$(JDBC_CURRENT_JDK_OPT_JAR_NAME)
JDBC_CURRENT_JDK_DEBUG_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_CURRENT_JDK_DEBUG_JAR_NAME)
JDBC_CURRENT_JDK_DMS_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_CURRENT_JDK_DMS_JAR_NAME)
JDBC_CURRENT_JDK_DMS_DEBUG_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_CURRENT_JDK_DMS_DEBUG_JAR_NAME)

JDBC_NEXT_JDK_OPT_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_NEXT_JDK_OPT_JAR_NAME)
JDBC_NEXT_JDK_SHIPHOME_OPT_JAR=$(JDBC_SHIPHOME_JAR_PATH)$(JDBC_NEXT_JDK_OPT_JAR_NAME)
JDBC_NEXT_JDK_DEBUG_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_NEXT_JDK_DEBUG_JAR_NAME)
JDBC_NEXT_JDK_DMS_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_NEXT_JDK_DMS_JAR_NAME)
JDBC_NEXT_JDK_DMS_DEBUG_JAR=$(JDBC_LABEL_JAR_PATH)$(JDBC_NEXT_JDK_DMS_DEBUG_JAR_NAME)

JDBCCLASSES14_JAR=$(ORACLE_HOME)/dbjava/lib/ojdbc5.jar


JDBCJAR4JAVAVM=$(ORACLE_HOME)/dbjava/lib/ojdbc4javavm.jar
JDBC_6_SERVER_JAR=$(ORACLE_HOME)/dbjava/lib/ojdbc6server.jar

TYPE2SERVERLIBNAME=jdbct2s$(JDBC_VERSION)
LOC_LIBT2SJDBC=$(JDBCHOME)lib/$(LIB_PREFIX)$(TYPE2SERVERLIBNAME).$(LIB_EXT)
LIBJDBC4JAVAVM=$(LOC_LIBT2SJDBC)
LLIBJDBC4JAVAVM=$(LDLIBFLAG)$(TYPE2SERVERLIBNAME)$(LIB_SUFFIX)

TYPE2SERVERLIBNAME_DEBUG=jdbct2s$(JDBC_VERSION)_g
LOC_LIBT2SJDBC_DEBUG=$(JDBCHOME)lib/$(LIB_PREFIX)$(TYPE2SERVERLIBNAME_DEBUG).$(LIB_EXT)
LIBJDBC4JAVAVM_DEBUG=$(LOC_LIBT2SJDBC_DEBUG)
LLIBJDBC4JAVAVM_DEBUG=$(LDLIBFLAG)$(TYPE2SERVERLIBNAME_DEBUG)$(LIB_SUFFIX)

JDBC_JNILIB_VERSION=$(RDBMS_VERSION)
OCIJDBCNAME=ocijdbc$(JDBC_JNILIB_VERSION)
HETEROXANAME = heteroxa$(JDBC_JNILIB_VERSION)

JDBCPUBH=$(I_SYM)$(JDBCHOME)if

JDBC_BASIC_ZIP=$(JDBC_PREVIOUS_JDK_SHIPHOME_OPT_JAR) \
    $(JDBC_CURRENT_JDK_SHIPHOME_OPT_JAR) \
    $(JDBC_NEXT_JDK_SHIPHOME_OPT_JAR) \
    $(ORACLE_HOME)$(DIRSEP)$(LIBDIR)$(DIRSEP)$(LIB_PREFIX)$(OCIJDBCNAME).$(SO_EXT)  

JDBC_EXTRA_ZIP=$(ORACLE_HOME)$(DIRSEP)$(LIBDIR)$(DIRSEP)$(LIB_PREFIX)$(HETEROXANAME).$(SO_EXT) 

JDBC_RPM_JARS=$(JDBC_PREVIOUS_JDK_OPT_JAR_NAME) \
   $(JDBC_CURRENT_JDK_OPT_JAR_NAME) \
   $(JDBC_NEXT_JDK_OPT_JAR_NAME)


JDBC_ALL_LRGS=  srto jnet jnet6 oct6 tct6 srtt \
t5cp t6cp o5cp o6cp cpro cprt tasm \
unt6 uno6 unt5 uno5 \
ein rlbt rlbo oct5 tct5 \
aao5 auo5 sao5 lao5 uto5 deo5 suo5 luo5 alo5 tro5 \
aat5 aut5 sat5 lat5 utt5 det5 sut5 lut5 alt5 trt5 \
aao6 auo6 sao6 lao6 uto6 deo6 suo6 luo6 alo6 tro6 ein6 \
aat6 aut6 sat6 lat6 utt6 det6 sut6 lut6 alt6 trt6 eat6 \
nunt1 \
5jow 5jo 5jopw 5jop 5jtw 5jta 5jtb 5jtc 5jtd 5jte 5jtpw 5jtp oei5 \
5pow 5po 5popw 5pop 5ptw  5pt 5ptpw 5ptp \
5gow 5go 5gopw 5gop 5gtwj 5gt 5gtpw 5gtp \
5dowa 5dowb 5dowc 5dowd 5dowe 5do 5dopw 5dow 5dtw 5dt 5dtpw 5dtp \
5dpow 5dpo 5dpopw 5dpop 5dptw 5dpt 5dptpw 5dptp \
5dgow 5dgo 5dgopw 5dgop 5dgtw 5dgt 5dgtpw 5dgtp \
6jow 6jo 6jopw 6jop 6jtw 6jta 6jtb 6jtc 6jtd 6jte 6jtf 6jtpw 6jtp oei6 \
6pow 6po 6popw 6pop 6ptw 6pt 6ptpw 6ptp \
6gow 6go 6gopw 6gop 6gtw 6gt 6gtpw 6gtp \
6dowa 6dowb 6dowc 6dowd 6dowe 6dowf 6do 6dopw 6dow 6dtw 6dt 6dtpw 6dtp \
6dpow 6dpo 6dpopw 6dpop 6dptw 6dpt 6dptpw 6dptp \
6dgow 6dgo 6dgopw 6dgop 6dgtw 6dgt 6dgtpw 6dgtp \
oei5z oei6z oei5l oei6l cc5j cc6j osf5 osf6 tsf5 tsf6 \
ipv6o5 ipv6t5 ipv6o6 ipv6t6 6joo 6jto 5joo 5jto 5jtxsv 6jtxsv \
op5a op5b op5c op5d op5e \
tw6a tw6b tw6c tw6d tw6e tw6f op6a op6b op6c op6d op6e op6f o6f t6f \
dlo5 dlt5 dlo6 dlt6 dlk5 dlts5 fnevt5 fnevt6 oidt5 oidt6 oido5 oido6
# Exiting /ade/b/1663622200/oracle/dbjava/exports.mk

# Entering /ade/b/1663622200/oracle/ctx/exports.mk



CTX_VERSION=11


LIBCTXSNAME=ctxs$(CTX_VERSION)
LIBCTXS = $(CTXLIB)$(LIB_PREFIX)$(LIBCTXSNAME).$(LIB_EXT)
LLIBCTXS = $(LDLIBFLAG)$(LIBCTXSNAME)$(LIB_SUFFIX)

LIBCTXWKLNAME=wkl
LIBCTXWK = $(CTXLIB)$(LIB_PREFIX)$(LIBCTXWKLNAME).$(LIB_EXT)
LLIBCTXWKL = $(LDLIBFLAG)$(LIBCTXWKLNAME)$(LIB_SUFFIX)

LIBCTXCNAME=ctxc$(CTX_VERSION)
LIBCTXC = $(CTXLIB)$(LIB_PREFIX)$(LIBCTXCNAME).$(LIB_EXT)
LLIBCTXC = $(LDLIBFLAG)$(LIBCTXCNAME)$(LIB_SUFFIX)

LIBCTXNAME=ctx$(CTX_VERSION)
LIBCTX = $(CTXLIB)$(LIB_PREFIX)$(LIBCTXNAME).$(LIB_EXT)
LLIBCTX = $(LDLIBFLAG)$(LIBCTXNAME)$(LIB_SUFFIX)
 
LIBZXNAME=zx$(CTX_VERSION)
LIBZX = $(CTXLIB)$(LIB_PREFIX)$(LIBZXNAME).$(LIB_EXT)
LLIBZX = $(LDLIBFLAG)$(LIBZXNAME)$(LIB_SUFFIX)
 
LIBGXNAME=gx$(CTX_VERSION)
LIBGX = $(CTXLIB)$(LIB_PREFIX)$(LIBGXNAME).$(LIB_EXT)
LLIBGX = $(LDLIBFLAG)$(LIBGXNAME)$(LIB_SUFFIX)
 
LIBINLXNAME=inlx$(CTX_VERSION)
LIBINLX = $(CTXLIB)$(LIB_PREFIX)$(LIBINLXNAME).$(LIB_EXT)
LLIBINLX = $(LDLIBFLAG)$(LIBINLXNAME)$(LIB_SUFFIX)

LIBINLXSONAME=inlxs$(CTX_VERSION)
LIBINLXSOOPT=$(CTXLIB)$(LIB_PREFIX)$(LIBINLXSONAME).$(SO_EXT)
LLIBINLXSO=$(LDLIBFLAG)$(LIBINLXSONAME)
LOC_LIBINLXSO=$(LIBINLXSOOPT)

 
CTX_LINK = $(LDPATHFLAG)$(CTXLIB) $(LLIBCTXC) $(LLIBCTX) $(LLIBZX) $(LLIBGX) $(LLIBCTX) $(LLIBZX) $(LLIBGX)

CTXHOME=$(ORACLE_HOME)/ctx/

CTXPUBH=$(I_SYM)$(CTXHOME)public

CTXLIB=$(CTXHOME)lib/

# Entering /ade/b/1663622200/oracle/ctx/s_exports.mk
# Exiting /ade/b/1663622200/oracle/ctx/s_exports.mk
# Exiting /ade/b/1663622200/oracle/ctx/exports.mk
# Entering /ade/b/1663622200/oracle/javavm/exports.mk
JAVAVMFORRDBMSBASENAME = javavm$(RDBMS_VERSION)
LIBJAVAVMFORRDBMSBASENAME = $(LIB_PREFIX)$(JAVAVMFORRDBMSBASENAME)
LIBJAVAVM=$(LIBHOME)$(LIBJAVAVMFORRDBMSBASENAME).$(LIB_EXT)
LLIBJAVAVM=$(LDLIBFLAG)$(JAVAVMFORRDBMSBASENAME)

# Entering /ade/b/1663622200/oracle/javavm/javavm_common.mk

# Exiting /ade/b/1663622200/oracle/javavm/javavm_common.mk
# Entering /ade/b/1663622200/oracle/javavm/s_exports.mk

# Exiting /ade/b/1663622200/oracle/javavm/s_exports.mk
# Exiting /ade/b/1663622200/oracle/javavm/exports.mk
# Entering /ade/b/1663622200/oracle/sqlplus/exports.mk

PRODUCT=sqlplus
SQLPLUSHOME=$(ORACLE_HOME)/sqlplus/
SQLPLUSLIBDIR=$(SQLPLUSHOME)$(LIBDIR)/

LIBSQLPLUSNAME = sqlplus
LIBISQLPLUSNAME= isqlplus
LIBSQLPLUSICNAME= sqlplusic
LIBSQLPLUSSO   = $(SQLPLUSLIBDIR)$(LIB_PREFIX)$(LIBSQLPLUSNAME).$(SO_EXT)
LIBSQLPLUS     = $(SQLPLUSLIBDIR)$(LIB_PREFIX)$(LIBSQLPLUSNAME).$(LIB_EXT)
LIBISQLPLUSSO  = $(SQLPLUSLIBDIR)$(LIB_PREFIX)$(LIBISQLPLUSNAME).$(SO_EXT)
LIBISQLPLUS    = $(SQLPLUSLIBDIR)$(LIB_PREFIX)$(LIBISQLPLUSNAME).$(LIB_EXT)
LIBSQLPLUSICSO = $(SQLPLUSLIBDIR)$(LIB_PREFIX)$(LIBSQLPLUSICNAME).$(SO_EXT)
LIBSQLPLUSIC   = $(SQLPLUSLIBDIR)$(LIB_PREFIX)$(LIBSQLPLUSICNAME).$(LIB_EXT)
LLIBSQLPLUS    = $(LDLIBFLAG)$(LIBSQLPLUSNAME)
LLIBISQLPLUS   = $(LDLIBFLAG)$(LIBISQLPLUSNAME)
LLIBSQLPLUSIC  = $(LDLIBFLAG)$(LIBSQLPLUSICNAME)

LIBMAIN        = $(SQLPLUSLIBDIR)s0afimai.$(OBJ_EXT)
LLIBMAIN       = $(SQLPLUSLIBDIR)s0afimai.$(OBJ_EXT)

SQLPLUSLIBS    = $(LLIBMAIN) $(LLIBSQLPLUS)
ISQLPLUSLIBS   = $(LLIBISQLPLUS) $(LLIBSQLPLUS)
SQLPLUSICLIBS  = $(LLIBSQLPLUSIC)

SQLPLUS        = $(SQLPLUSBINDIR)sqlplus$(HYBRID_SUFFIX)$(EXE_SUFFIX)

SQLPLUSADMINDIR=$(SQLPLUSHOME)admin/
SQLPLUSBINDIR=$(SQLPLUSHOME)$(BINDIR)/

# Entering /ade/b/1663622200/oracle/sqlplus/s_exports.mk

SHARED_LDFLAG=-G -L$(SQLPLUSHOME)lib -L$(ORACLE_HOME)/lib -R$(ORACLE_HOME)/lib -o
LDSYMSTRIP=-s
S_LDOPTS=-h $(LIB_PREFIX)$(LIBSQLPLUSNAME).$(SO_EXT) $(LDSYMSTRIP) \
-u afidrv -z defs -lc

HELPINS=$(SQLPLUSBINDIR)helpins
# Exiting /ade/b/1663622200/oracle/sqlplus/s_exports.mk
# Exiting /ade/b/1663622200/oracle/sqlplus/exports.mk
 
# Entering /ade/b/1663622200/oracle/precomp/exports.mk

TOP=$(ORACLE_HOME)/precomp

PRECOMP_VERSION=11
LIBSQLNAME=sql$(PRECOMP_VERSION)
LLIBSQL=$(LDLIBFLAG)$(ILIB_PREFIX)$(LIBSQLNAME)$(ILIB_SUFFIX)
LIBSQL=$(LIBHOME)$(LIB_PREFIX)$(LIBSQLNAME).$(DEPLIB_EXT)

PRECOMP_PRD=precomp
PRECOMPHOME=$(ORACLE_HOME)/precomp/
PRECOMPADMIN=$(PRECOMPHOME)admin/
PRECOMPLIB=$(PRECOMPHOME)$(LIBDIR)/

OTTCLASSESZIP=$(PRECOMPLIB)ottclasses.$(ZIP_EXT)

PRECOMPPUBH=$(I_SYM)$(PRECOMPHOME)public $(I_SYM)$(PRECOMPHOME)include

LIBSQLSHNAME=sqlsh$(PRECOMP_VERSION)
LLIBSQLSH=$(LDLIBFLAG)$(LIBSQLSHNAME)$(LIB_SUFFIX)

# Entering /ade/b/1663622200/oracle/precomp/s_exports.mk
 
# Exiting /ade/b/1663622200/oracle/precomp/s_exports.mk
# Exiting /ade/b/1663622200/oracle/precomp/exports.mk

PRODUCT=precomp

PRECOMPADALIB=$(PRECOMPHOME)pubsrc/adalib/
PRECOMPBIN=$(PRECOMPHOME)$(BINDIR)/
PRECOMPDEMO=$(PRECOMPHOME)demo/
PRECOMPINCLUDE=$(PRECOMPHOME)include/
PRECOMPINSTALL=$(PRECOMPHOME)install/
PRECOMPMESG=$(PRECOMPHOME)mesg/
PRECOMPSRC=$(PRECOMPHOME)src/
PRECOMPUTL=$(PRECOMPHOME)utl/
PRECOMPPUBLIC=$(PRECOMPHOME)public/

OTTCLASS=$(PRECOMPHOME)classes/
JAVAC=$(JDK_HOME)/bin/javac
JAVAC_MEM_FLAG = -J-mx64m

UTL_SCRIPTS = \
        ott \

PRODLIBHOME=$(PRECOMPLIB)


LIBFIDLNAME=fidl
LIBMODNAME=mod
LIBPCCNAME=pcc
LIBPFONAME=pfo
LIBPGPNAME=pgp
LIBPPLNAME=ppl
LIBPROC2NAME=proc2
LIBPROCOB2NAME=procob2
LIBPSDNAME=psd
LIBSQXNAME=sqx8

LIBFIDL=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBFIDLNAME).$(LIB_EXT)
LIBMOD=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBMODNAME).$(LIB_EXT)
LIBPCC=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBPCCNAME).$(LIB_EXT)
LIBPFO=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBPFONAME).$(LIB_EXT)
LIBPGP=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBPGPNAME).$(LIB_EXT)
LIBPPL=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBPPLNAME).$(LIB_EXT)
LIBPROC2=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBPROC2NAME).$(LIB_EXT)
LIBPROCOB2=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBPROCOB2NAME).$(LIB_EXT)
LIBPSD=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBPSDNAME).$(LIB_EXT)
LIBSQX=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBSQXNAME).$(LIB_EXT)

LOC_LIBSQL=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBSQLNAME).$(LIB_EXT)

LIBS=$(PRODLIBHOME)$(LIB_PREFIX)$(LIBSQLNAME).$(LIB_EXT)

PRECOMP_LIBS=$(LIBFIDL) $(LIBMOD) $(LIBPCC) $(LIBPFO) \
	$(LIBPGP) $(LIBPPL) $(LIBPROC2) $(LIBPROCOB2) $(LIBPSD) $(LOC_LIBSQL)

SHLIBS=$(PRODSOHOME)$(LIB_PREFIX)$(LIBSQLNAME).$(SO_EXT)
 
COB2MAIN=$(PRECOMPLIB)spcbd.$(OBJ_EXT)
FIDLMAIN=$(PRECOMPLIB)ilmain.$(OBJ_EXT)
FORMAIN=$(PRECOMPLIB)spc1drv.$(OBJ_EXT)
MODADAMAIN=$(PRECOMPLIB)pmsapr.$(OBJ_EXT) $(PRECOMPLIB)spmmain.$(OBJ_EXT)
PLIMAIN=$(PRECOMPLIB)spc3drv.$(OBJ_EXT)
 
PD1OBJ=pd1.$(OBJ_EXT)
PDAOBJ=pda.$(OBJ_EXT)
PDBOBJ=pdb.$(OBJ_EXT)
PDCOBJ=pdc.$(OBJ_EXT)
PDFOBJ=pdf.$(OBJ_EXT)
PDSOBJ=pds.$(OBJ_EXT)
CODEGENOBJS=$(PD1OBJ) $(PDAOBJ) $(PDCOBJ) $(PDBOBJ) $(PDFOBJ) $(PDSOBJ)

ADAPDC=$(PRECOMPLIB)$(PDAOBJ) $(PRECOMPLIB)$(PDSOBJ)
CPDC=$(PRECOMPLIB)$(PDCOBJ) $(PRECOMPLIB)$(PDSOBJ)
COBPDC=$(PRECOMPLIB)$(PDBOBJ) $(PRECOMPLIB)$(PDSOBJ)
FORPDC=$(PRECOMPLIB)$(PDFOBJ) $(PRECOMPLIB)$(PDSOBJ)
PLIPDC=$(PRECOMPLIB)$(PD1OBJ) $(PRECOMPLIB)$(PDSOBJ)

PRECOMP_OBJFILES=$(ADAPDC) $(CPDC) $(COBPDC) $(FORPDC) $(PLIPDC) \
		 $(COB2MAIN) $(FIDLMAIN) $(FORMAIN) $(MODADAMAIN) $(PLIMAIN)

PRECOMPPUBH32=

PRECOMPH=$(I_SYM)$(PRECOMPHOME)hdrs
PRECOMPSH=$(PRECOMPH) $(PRECOMPPUBH32) $(PRECOMPPUBH)

INCLUDE=$(PRECOMPSH) $(PLSQLPUBH) $(RDBMSPUBH) $(ORACOREPUBH) $(NLSRTLPUBH) \
	$(OTRACEPUBH) $(SSLPUBH) $(NETWORKPUBH) $(SLAXPUBH) $(JAVAVMPUBH) $(OTHER_H) $(I_SYM).


STATICPROLDLIBS=$(STATIC_LDCLIENTLIBS) $(LLIBTHREAD)
DYNAMICPROLDLIBS=$(SHARED_LDCLIENTLIBS) $(LLIBTHREAD)
PROLDLIBS=$(DYNAMICPROLDLIBS)
LLIBCLNTSHS=-lsqlsh$(PRECOMP_VERSION)

STATICCPPLDLIBS=$(STATIC_LDCLIENTLIBS)
DYNAMICCPPLDLIBS=$(SHARED_LDCLIENTLIBS)
CPPLDLIBS=$(DYNAMICCPPLDLIBS)

COBOL_STATICPROLDLIBS=$(STATIC_CLIENTLIBS) $(COBLDLIBS) $(LLIBTHREAD)
COBOL_DYNAMICPROLDLIBS=$(SHARED_CLIENTLIBS) $(COBLDLIBS) $(LLIBTHREAD)
COBOL_PROLDLIBS=$(COBOL_DYNAMICPROLDLIBS)

LIBPLS_CLT=$(LPLSQLLIBS)

OTT=ott$(EXE_SUFFIX)
MODADA=modada$(EXE_SUFFIX)
PROC=proc$(EXE_SUFFIX)
PROCOB=procob$(EXE_SUFFIX)
PROFOR=profor$(EXE_SUFFIX)
PROPLI=propli$(EXE_SUFFIX)
RTSORA=rtsora$(EXE_SUFFIX)

LOC_MODADA=$(PRECOMPBIN)$(MODADA)
LOC_PROC=$(PRECOMPBIN)$(PROC)
LOC_PROCOB=$(PRECOMPBIN)$(PROCOB)
LOC_PROFOR=$(PRECOMPBIN)$(PROFOR)
LOC_PROPLI=$(PRECOMPBIN)$(PROPLI)
LOC_RTSORA=$(PRECOMPBIN)$(RTSORA)

MODADA_LINKLINE=$(LINK) $(MODADAMAIN) $(LIBMOD) $(ADAPDC) $(LIBSLAX) \
		$(LIBPGP) $(LLIBPLSQL) $(LLIBSNLSRTL) $(LLIBUNLSRTL) \
		$(LLIBNLSRTL) $(DEF_ON) $(SSCOREED) $(LINKTTLIBS)

PROC_LINKLINE=$(LINK) $(S0MAIN) $(CPDC) $(LIBPROC2) $(LIBSLAX) \
	      $(LIBPGP) $(LLIBPLSQL) $(LIBPLCN) $(LLIBSNLSRTL) $(LLIBUNLSRTL) \
	      $(LLIBNLSRTL) $(DEF_ON) $(LINKTTLIBS)

PROCOB_LINKLINE=$(LINK) $(COB2MAIN) $(LIBPROCOB2) $(LIBSLAX) $(COBPDC) \
	        $(LIBPGP) $(DEF_ON) $(LLIBPLSQL) $(LIBPROCOB2) $(LLIBPLSQL) \
		$(LIBPLCN) \
	        $(LLIBSNLSRTL) $(LLIBUNLSRTL) $(LLIBNLSRTL) $(SSCOREED) \
		$(LINKTTLIBS)

PROFOR_LINKLINE=$(LINK) $(FORMAIN) $(FORPDC) $(LIBPFO) \
		$(LIBPCC) $(LIBPGP) $(LLIBPLSQL) $(LIBPSD) $(LIBSLAX) \
		$(LLIBPLSQL) $(LIBPLCN) $(LIBPSD) \
		$(LLIBSNLSRTL) $(LLIBUNLSRTL) \
		$(LLIBNLSRTL) $(DEF_ON) $(SSCOREED) $(LINKTTLIBS)

PROPLI_LINKLINE=$(LINK) $(PLIMAIN) $(PLIPDC) $(LIBPPL) $(LIBPCC) \
		$(LIBPGP) $(LLIBPLSQL) $(LIBSLAX) $(LIBPSD) $(LLIBPLSQL) \
		$(LIBPLCN) $(LIBPSD) \
		$(LLIBSNLSRTL) $(LLIBUNLSRTL) $(LLIBNLSRTL) \
		$(DEF_ON) $(SSCOREED) $(LINKTTLIBS)

RTSORA_LINKLINE=$(PLATFORM_PREFIX_RTSORA) \
		$(COB) -o $(LOC_RTSORA) -t -xe "" $(RTSPORTFLAGS) \
		$(COBSQLINTF) $(SCOREPT) $(SSCOREED) $(DEF_ON) $(LDPATHFLAG) \
		$(LIBHOME) $(LLIBCLNTSH)

EXE_PROT=755


DEMO_PROC_BUILD_SHARED=$(CC) $(LFLAGS) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(PROLDLIBS)
DEMO_PROC_BUILD_STATIC=$(CC) $(LFLAGS) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(STATICPROLDLIBS)
DEMO_PROC_CPPBUILD_SHARED=$(CPLUSPLUS) $(LFLAGS) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(CPPLDLIBS)
DEMO_PROC_CPPBUILD_STATIC=$(CPLUSPLUS) $(LFLAGS) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(STATICCPPLDLIBS)
PCC2C=$(PROC) $(PROCFLAGS) iname=$(PCCSRC) $(INCLUDE)
C2O=$(CC) $(CFLAGS) -c $*.c
CPP2O_EXE=$(CPLUSPLUS) $(LFLAGS) -c $(INCLUDE) $(EXE).c
CPP2O=$(CPLUSPLUS) $(LFLAGS) -c $(INCLUDE) $*.c

DEMO_PROCOB_BUILD_SHARED=$(COB) $(COBFLAGS) -o $(EXE) $(COBS) $(LDPATHFLAG)$(LIBHOME) $(COBSQLINTF) $(COBOL_PROLDLIBS)
DEMO_PROCOB_BUILD_STATIC=$(COB) $(COBFLAGS) -o $(EXE) $(COBS) $(LDPATHFLAG)$(LIBHOME) $(COBSQLINTF) $(COBOL_STATICPROLDLIBS)
COB2GNT=$(COB) $(COBGNTFLAGS) $*.cob

DEMO_PROFOR_BUILD_SHARED=$(FC) $(FCFLAGS) -o $(EXE) $(FORS) $(FC_LDPATHFLAG)$(LIBHOME) $(PROLDLIBS)
DEMO_PROFOR_BUILD_STATIC=$(FC) $(FCFLAGS) -o $(EXE) $(FORS) $(FC_LDPATHFLAG)$(LIBHOME) $(STATICPROLDLIBS)
F2O=$(FC) $(FCFLAGS) -c $*.f

LIBDIR32=lib32

PROC_32=$(PROC)
DEMO_PROC_BUILD_SHARED_32=$(CC) $(LFLAGS32) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(PROLDLIBS)
DEMO_PROC_BUILD_STATIC_32=$(CC) $(LFLAGS32) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(STATICPROLDLIBS)
DEMO_PROC_CPPBUILD_SHARED_32=$(CPLUSPLUS) $(LFLAGS32) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(CPPLDLIBS)
DEMO_PROC_CPPBUILD_STATIC_32=$(CPLUSPLUS) $(LFLAGS32) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(STATICCPPLDLIBS)
C2O_32=$(CC) $(CFLAGS32) -c $*.c
CPP2O_EXE_32=$(CPLUSPLUS) $(LFLAGS32) -c $(INCLUDE) $(EXE).c
CPP2O_32=$(CPLUSPLUS) $(LFLAGS32) -c $(INCLUDE) $*.c
CFLAGS32=$(CFLAGS)
LFLAGS32=

PROCOB_32=$(PROCOB)
DEMO_PROCOB_BUILD_SHARED_32=$(DEMO_PROCOB_BUILD_SHARED)
DEMO_PROCOB_BUILD_STATIC_32=$(DEMO_PROCOB_BUILD_STATIC)
COB2GNT_32=$(COB2GNT)

PROFOR_32=$(PROFOR)
DEMO_PROFOR_BUILD_SHARED_32=$(DEMO_PROFOR_BUILD_SHARED)
DEMO_PROFOR_BUILD_STATIC_32=$(DEMO_PROFOR_BUILD_STATIC)
F2O_32=$(F2O)

LIBDIR64=lib64

PROC_64=$(PROC)
DEMO_PROC_BUILD_SHARED_64=$(CC) $(LFLAGS64) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(PROLDLIBS)
DEMO_PROC_BUILD_STATIC_64=$(CC) $(LFLAGS64) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(STATICPROLDLIBS)
DEMO_PROC_CPPBUILD_SHARED_64=$(CPLUSPLUS) $(LFLAGS64) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(CPPLDLIBS)
DEMO_PROC_CPPBUILD_STATIC_64=$(CPLUSPLUS) $(LFLAGS64) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(STATICCPPLDLIBS)
C2O_64=$(CC) $(CFLAGS64) -c $*.c
CPP2O_EXE_64=$(CPLUSPLUS) $(LFLAGS64) -c $(INCLUDE) $(EXE).c
CPP2O_64=$(CPLUSPLUS) $(LFLAGS64) -c $(INCLUDE) $*.c
CFLAGS64=$(CFLAGS)
LFLAGS64=

PROCOB_64=$(PROCOB)
DEMO_PROCOB_BUILD_SHARED_64=$(DEMO_PROCOB_BUILD_SHARED)
DEMO_PROCOB_BUILD_STATIC_64=$(DEMO_PROCOB_BUILD_STATIC)
COB2GNT_64=$(COB2GNT)

PROFOR_64=$(PROFOR)
DEMO_PROFOR_BUILD_SHARED_64=$(DEMO_PROFOR_BUILD_SHARED)
DEMO_PROFOR_BUILD_STATIC_64=$(DEMO_PROFOR_BUILD_STATIC)
F2O_64=$(F2O)




INSTALL_SHORTCUT_TARGETS=$(MODADA) $(PROC) $(PROCOB) \
			 $(PROFOR) $(PROPLI) $(RTSORA)
INSTALL_SHORTCUT_32_64_TARGETS=
INSTALL_RENAMED_32_64_TARGETS=

LOC_LIBSQLSH=$(PRECOMPLIB)$(LIB_PREFIX)$(LIBSQLSHNAME).$(SO_EXT)


IS_EXIST=test ! -f

# Entering /ade/b/1663622200/oracle/precomp/s_precomp.mk


LLIBCLNTSH=$(LDLIBFLAG)$(LIBCLNTSHNAME) -b rtl
PROC_LINKLINE += -bbigtoc
PROCOB_LINKLINE += -bbigtoc

ASFLAGS=

LLAIO=
LLIBTHREAD=-lc_r -lpthreads

SYS_INCLUDE_PATH=/usr/include
SYS_INCLUDE='sys_include=($(ORACLE_HOME)/precomp/public,$(SYS_INCLUDE_PATH))'
PCSCFG_SYS_INCLUDE='sys_include=($$ORACLE_HOME/precomp/public,$(SYS_INCLUDE_PATH))'
PCSCFG=pcscfg.cfg

INSTALL_SHORTCUT_TARGETS=$(MODADA) $(PROC) $(PROCOB) \
        $(PROPLI) $(RTSORA)

INSTALL_SHORTCUT_32_64_TARGETS=$(PROCOB_32) $(RTSORA_32)
INSTALL_RENAMED_32_64_TARGETS=

CPLUS_SYS_INCLUDE='sys_include=($(ORACLE_HOME)/precomp/public,/usr/vacpp/include,$(SYS_INCLUDE_PATH),/usr/vacpp/include)'
CPLUS_INCLUDE= $(I_SYM)$(PRECOMPDEMO)proc $(INCLUDE)
CPLUS_CFLAGS=$(OPTIMIZE) $(INCLUDE) -DSLTS_ENABLE -D_REENTRANT
CCP=/bin/xlC_r
CPLUSPLUS=xlC -+ -q64
CPLUSPLUS32=xlC
LIBOBK=-lobk

DYNAMICPROLDLIBS=$(LLIBCLNTSH) $(LDLIBS) $(LLIBTHREAD)

MODADALIB=$(PRECOMPHOME)pubsrc/adalib/adalib/

ADAPORT=powerada
ADACC=abuild -vF -p -Lalib.list
ADALD=abuild -vF -p -Lalib.list -b
ADACLEAN=alibrm -F adalib
INS_ADA_COMPILE=compile_powerada
INS_ADA_CLEAN=clean_powerada


EXECS=$(LOC_MODADA) $(LOC_OTT) $(LOC_PROC) $(LOC_PROCOB32) $(LOC_PROCOB18) $(LOC_PROFOR) $(LOC_PROPLI) $(LOC_RTSORA)



ada_powerada: env_$(ADAPORT) $(OBJS)
	$(ADACC) $(OBJS)
	$(RMF) adalib/.adalinks
	$(ECHO) -L$(ORACLE_HOME)/lib32 | tr ' ' '\n' >> adalib/.adalinks
	$(ECHO) $(PROLDLIBS) | tr ' ' '\n' >> adalib/.adalinks
	$(ADALD) $(EXE) -o $(EXE)

env_powerada: GVAS_table

GVAS_table:
	-echo 1 | alibinit > /dev/null
	echo $(ORACLE_HOME)/precomp/pubsrc/adalib/adalib >> alib.list

COB=cob
COBFLAGS=-C IBMCOMP -C NESTCALL -x -t
COBGNTFLAGS=-C IBMCOMP -C NESTCALL -u
GNT=.gnt
COBSQLINTF=$(PRECOMPLIB)cobsqlintf.o

PROCOB_32=procob32
RTSORA_32=rtsora32
COB_32=cob32
DEMO_PROCOB_BUILD_SHARED_32=$(COB_32) $(COBFLAGS) -o $(EXE) $(COBS) $(LDPATHFLAG)$(LIBHOME) $(COBSQLINTF) $(COBOL_PROLDLIBS)
DEMO_PROCOB_BUILD_STATIC_32=$(COB_32) $(COBFLAGS) -o $(EXE) $(COBS) $(LDPATHFLAG)$(LIBHOME) $(COBSQLINTF) $(COBOL_STATICPROLDLIBS)

RTSPORTFLAGS=

RESOLVE_SQLROWIDGET = -I SQLRowidGet

S_LINK=s_link.mk
LINK32=ld -b32 $(LDFLAGS32) 

RTSORA_LINKLINE=$(COB) -o $(LOC_RTSORA) -t -xe "" $(RTSPORTFLAGS) $(RESOLVE_SQLROWIDGET) $(COBSQLINTF)\
       $(SCOREPT) $(SSCOREED) $(DEF_ON) -L $(LIBHOME) $(LLIBSQL) $(NAETTOBJS) $(LLIBXSD) $(COBTTLIBS)

RTSORA_LINKLINE32=$(RTSORA_LINKLINE)


FC=f77
FCFLAGS=
FCFLAGS32=-q32
FC_LDPATHFLAG=$(LDPATHFLAG)
PROFOR_32=profor

STATICPROLDLIBS=$(STATIC_ORACLETTLIBS) $(LDLIBS) $(LLIBTHREAD) $(AIXIMP)
COBOL_STATICPROLDLIBS=$(STATIC_ORACLETTLIBS) $(COBLDLIBS) $(LLIBTHREAD) $(RTSPORTFLAGS)
COBOL_DYNAMICPROLDLIBS=$(LLIBCLNTSH) $(COBLDLIBS) $(LLIBTHREAD)

CFLAGS32=$(GFLAG) $(OPTIMIZE) $(CDEBUG) $(CCFLAGS32) $(PFLAGS) $(SHARED_CFLAG) $(USRFLAGS)
CFLAGS64=$(CFLAGS)
LFLAGS64=$(ASFLAGS)

PROFOR_LINKLINE=$(LINK) $(FORMAIN) $(FORPDC) $(LIBPFO) \
                $(LIBPCC) $(LIBPGP) $(LLIBPLSQL) $(LIBPSD) $(LIBSLAX) \
                $(LLIBPLSQL) $(LIBPLCN) $(LIBPSD) \
                $(LLIBSNLSRTL) $(LLIBUNLSRTL) \
                $(LLIBNLSRTL) $(DEF_ON) $(SSCOREED) $(LINKTTLIBS) -bbigtoc

LIBDIR32=lib32
LIBDIR64=lib
LIBHOME32=$(ORACLE_HOME)/$(LIBDIR32)

PRODLIBHOME32=$(PRODHOME)/$(LIBDIR32)/
LDFLAGS32="-b32 -o $(PRODLIBHOME32)$@ -L$(PRODLIBHOME32) -L$(LIBHOME32)"



JAVACLASSDIR=$(ORACLE_HOME)/precomp/classes/
JDK_HOME=$(ORACLE_HOME)jdk

CLASS_SEP=:
DIRSEP=/

JAVACLASSPATH=.$(CLASS_SEP)$(JAVACLASSDIR)$(CLASS_SEP)$(ORACLE_HOME)/jdbc/lib/ojdbc14.jar$(CLASS_SEP)$(ORACLE_HOME)/jlib/orai18n.jar:$(ORACLE_HOME)/precomp/lib/ottclasses.zip

ZIP=zip

SHIPHOME_JRE_LOCATION=/usr/lpp/JRE1.1.8
SHIPHOME_JRE_RUNCMD=jre
SHIPHOME_JRE_JRECLASSFILE=$(SHIPHOME_JRE_LOCATION)/lib/rt.jar:$(SHIPHOME_JRE_LOCATION)/lib/i18n.jar
SHIPHOME_JRE_JDBCCLASSFILE=classes111.zip
SHIPHOME_JRE_SSLCLASSFILE=$$ORACLE_HOME/jlib/oraclepki.jar:$$ORACLE_HOME/jlib/osdt_core.jar:$$ORACLE_HOME/jlib/osdt_cert.jar

SHIPHOME_JDK_LOCATION=$$ORACLE_HOME/jdk
SHIPHOME_JDK_RUNCMD=java
SHIPHOME_JDK_JDKCLASSFILE=
SHIPHOME_JDK_JDBCCLASSFILE=$$ORACLE_HOME/jdbc/lib/ojdbc5.jar
SHIPHOME_JDK_NLSCLASSFILE=$$ORACLE_HOME/jlib/orai18n.jar
SHIPHOME_JDK_SSLCLASSFILE=$$ORACLE_HOME/jlib/oraclepki.jar:$$ORACLE_HOME/jlib/osdt_core.jar:$$ORACLE_HOME/jlib/osdt_cert.jar
SHIPHOME_JDK_JVMCLASSFILE=$$ORACLE_HOME/javavm/lib/aurora.zip
SHIPHOME_JDK_OTTCLASSFILE=$$ORACLE_HOME/precomp/lib/ottclasses.zip

SHLIBS=
NEW_LD_SHLIBS=$(LOC_LIBSQLSH)
DEPDIRS=-L $(ORACLE_HOME)/rdbms/lib -L $(ORACLE_HOME)/plsql/lib -L $(ORACLE_HOME)/network/lib
PCTINA=$(PRECOMPLIB)pctina.$(OBJ_EXT)
libsqlsh10LIBS=$(DEPDIRS) $(PCTINA) $(DEF_OPT) $(LLIBCLIENTSH) $(LLIBGENERICSH) $(LLIBCOMMONSH)\
               $(LLIBPLSSH) $(LLIBCORE_SH) $(LLIBNLSSH) -lnsl -ldl -lm -lc
libsqlsh10EXTRALIBS=$(NNZ_DEP)

CPDEMO_FLAG=define=_POSIX_SOURCE

DEMO_PROC_BUILD_SHARED=$(DEMO_PROC_BUILD_SHARED_64)
DEMO_PROC_BUILD_STATIC=$(DEMO_PROC_BUILD_STATIC_64)
DEMO_PROC_CPPBUILD_SHARED=$(DEMO_PROC_CPPBUILD_SHARED_64)
DEMO_PROC_CPPBUILD_STATIC=$(DEMO_PROC_CPPBUILD_STATIC_64)
C++2O_EXE=$(C++2O_EXE_64)
C++2O=$(C++2O_64)
DEMO_PROC_CPPBUILD_SHARED_32=$(CPLUSPLUS32) $(LFLAGS32) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(CPPLDLIBS)
DEMO_PROC_CPPBUILD_STATIC_32=$(CPLUSPLUS32) $(LFLAGS32) -o $(EXE) $(OBJS) $(LDPATHFLAG)$(LIBHOME) $(STATICCPPLDLIBS)
CPP2O_EXE_32=$(CPLUSPLUS32) $(LFLAGS32) -c $(INCLUDE) $(EXE).c
CPP2O_32=$(CPLUSPLUS32) $(LFLAGS32) -c $(INCLUDE) $*.c
LFLAGS32=-+ -q32

DEMO_PROFOR_BUILD_SHARED_32=$(FC) $(FCFLAGS32) -o $(EXE) $(FORS) $(FC_LDPATHFLAG)$(LIBHOME) $(PROLDLIBS)
DEMO_PROFOR_BUILD_STATIC_32=$(FC) $(FCFLAGS32) -o $(EXE) $(FORS) $(FC_LDPATHFLAG)$(LIBHOME) $(STATICPROLDLIBS)
F2O_32=$(FC) $(FCFLAGS32) -c $*.f


PL_LINK_OVERRIDES=RTSORA=$(RTSORA_32) \
                  COB=$(COB_32)       \
                  PROCOB=$(PROCOB_32) \
                  LIBDIR=$(LIBDIR32)  \
                  LDFLAGS=$(LDFLAGS32) \
		LD=ld

ADACFG=pccada.cfg
CCFG=pccc.cfg
FORCFG=pccfor.cfg
OTTCFG=ottcfg.cfg
PCBCFG=pcbcfg.cfg
PCSCFG=pcscfg.cfg
PLICFG=pccpli.cfg
PMSCFG=pmscfg.cfg

config:
	$(RMF) $(CONFIG)
	$(TOUCH) $(CONFIG)


PCBCFG_LINKLINE=(\
	$(MAKE) -f $(ORACLE_HOME)/precomp/lib/ins_precomp.mk CONFIG=$(PCBCFG) config;\
	$(ECHO) comp5=yes >> $(PCBCFG);\
	$(ECHO) define=comp5 >> $(PCBCFG);\
	$(ECHO) define=bit64 >> $(PCBCFG);\
)

PATH_IC='sys_include=($$ORACLE_HOME/sdk/include,$(SYS_INCLUDE_PATH))'

PCSCFG_LINKLINE=(\
	$(MAKE) CONFIG=$(PCSCFG) config;\
	$(ECHO) $(PCSCFG_SYS_INCLUDE) >> $(PCSCFG);\
	$(ECHO) "ltype=short" >> $(PCSCFG);\
	$(ECHO) "define=__64BIT__" >> $(PCSCFG);\
	$(ECHO) "define=_IBM_C" >> $(PCSCFG);\
	$(ECHO) "define=_LONG_LONG" >> $(PCSCFG);\
)

# Exiting /ade/b/1663622200/oracle/precomp/s_precomp.mk
# Exiting precomp.mk
# Entering /ade/b/1663622200/oracle/buildtools/mkfile/libclntsh.mk
$(LIBCLNTSH_NPT) $(LIBCLNTSH): ${LIBHOME}libclient11.$(LIB_EXT) ${LIBHOME}libsql11.$(LIB_EXT) \
	${LIBHOME}libntcp11.$(LIB_EXT)	${LIBHOME}libn11.$(LIB_EXT) \
        ${LIBHOME}libnl11.$(LIB_EXT)	${LIBHOME}libnldap11.$(LIB_EXT) \
        ${LIBHOME}libnhost11.$(LIB_EXT)	${LIBHOME}libntns11.$(LIB_EXT) \
        ${LIBHOME}libnoname11.$(LIB_EXT) ${LIBHOME}libnus11.$(LIB_EXT) \
        ${LIBHOME}libntcps11.$(LIB_EXT)	${LIBHOME}libnro11.$(LIB_EXT) \
	${LIBHOME}libnsslb11.$(LIB_EXT)	${LIBHOME}libcommon11.$(LIB_EXT)\
	${LIBHOME}libgeneric11.$(LIB_EXT) ${LIBHOME}libmm.$(LIB_EXT)\
	${LIBHOME}libnls11.$(LIB_EXT)	${LIBHOME}libcore11.$(LIB_EXT)\
	${RDBMSLIB}xaondy.$(OBJ_EXT)
	$(SILENT)$(ECHO) "Building client shared library libclntsh.$(SO_EXT) ..."
	$(SILENT)$(ECHO) "Call script $$ORACLE_HOME/bin/genclntsh ..."
	$(GENCLNTSH)
	$(SILENT)$(ECHO) "Built $$ORACLE_HOME/${LIBDIR}/libclntsh.$(SO_EXT) ... DONE"

ALLSHLIBS=$(VARLIBS) $(LD_SHLIBS) $(DLOPENLIBS) $(NEW_LD_SHLIBS) $(NEW_DLOPENLIBS)
shlibs: $(ALLSHLIBS)
bootstraplibs: $(CUS_BOOTSTRAPLIBS)

$(LD_SHLIBS) ld_shlibs_target: $(ALWAYS)
	$(CUS_SHLIB_COMMAND)

$(DLOPENLIBS) dlopenlibs_target: $(ALWAYS)
	$(CUS_DLOPENLIB_COMMAND)

$(NEW_LD_SHLIBS) new_ld_shlibs_target: $(ALWAYS)
	$(CUS_NEW_SHLIB_COMMAND)

$(NEW_DLOPENLIBS) new_dlopenlibs_target: $(ALWAYS)
	$(CUS_NEW_DLOPENLIB_COMMAND)

$(VARLIBS) varlibs_target: $(ALWAYS)
	$(CUS_VARLIB_COMMAND)

$(CUS_BOOTSTRAPLIBS) bootstraplib_target: $(ALWAYS)
	$(CUS_BOOTSTRAPLIB_COMMAND)

ld_shlib:
	$(LD_SHLIB_COMMAND)

dlopenlib:
	$(DLOPENLIB_COMMAND)

new_ld_shlib:
	$(NEW_LD_SHLIB_COMMAND)

new_dlopenlib:
	$(NEW_DLOPENLIB_COMMAND)

bootstrap:
	$(BOOTSTRAPLIB_COMMAND)

always:
# Exiting /ade/b/1663622200/oracle/buildtools/mkfile/libclntsh.mk
